# Generated by Django 5.1.6 on 2025-05-03 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0003_prompt_parent"),
        ("users", "0002_user_vector_db"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_prompt",
            field=models.ForeignKey(
                blank=True,
                help_text="The default prompt for this user, if set.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_users",
                to="prompts.prompt",
                verbose_name="Default Prompt",
            ),
        ),
    ]
