# Generated by Django 5.1.8 on 2025-05-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_default_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chunk_size",
            field=models.IntegerField(
                default=1000,
                help_text="Size of text chunks for document processing.",
                verbose_name="Chunk Size",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="overlap_size",
            field=models.IntegerField(
                default=200,
                help_text="Size of overlap between text chunks",
                verbose_name="Overlap Size",
            ),
        ),
    ]
