# Generated by Django 5.1.8 on 2025-05-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_chunk_size_user_overlap_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="chunk_size",
            field=models.IntegerField(
                default=500,
                help_text="Size of text chunks for document processing.",
                verbose_name="Chunk Size",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="overlap_size",
            field=models.IntegerField(
                default=100,
                help_text="Size of overlap between text chunks",
                verbose_name="Overlap Size",
            ),
        ),
    ]
