# Generated by Django 5.1.8 on 2025-05-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_chunk_size_alter_user_overlap_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessCodeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "max_capacity",
                    models.IntegerField(
                        help_text="Maximum number of users that can use this access code group"
                    ),
                ),
                (
                    "current_usage",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this access code has been used",
                    ),
                ),
                (
                    "access_code",
                    models.CharField(
                        help_text="Unique registration code for this group",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this access code is currently active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Access Code Group",
                "verbose_name_plural": "Access Code Groups",
            },
        ),
    ]
