# Generated by Django 5.1.11 on 2025-07-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_access_code_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_source",
            field=models.CharField(
                choices=[("DARE", "DARE"), ("SocraticBooks", "SocraticBooks")],
                default="DARE",
                help_text="Platform where the user was originally authenticated",
                max_length=50,
                verbose_name="Authentication Source",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_dare_accessible",
            field=models.BooleanField(
                default=True,
                help_text="Whether this user can access DARE platform",
                verbose_name="DARE Access",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_socratic_books_accessible",
            field=models.BooleanField(
                default=False,
                help_text="Whether this user can access SocraticBooks platform",
                verbose_name="SocraticBooks Access",
            ),
        ),
    ]
