# Generated by Django 5.1.11 on 2025-07-18 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0021_alter_llm_provider_modelgroup'),
        ('users', '0008_user_auth_source_user_is_dare_accessible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='model_group',
            field=models.ForeignKey(blank=True, help_text='Model group that determines which LLM models this user can access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='conversations.modelgroup', verbose_name='Model Group'),
        ),
    ]
