# Generated by Django 5.1.11 on 2025-07-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_model_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesscodegroup",
            name="scope",
            field=models.CharField(
                choices=[("DARE", "DARE Only"), ("DUAL", "DARE + SocraticBooks")],
                default="DARE",
                help_text="Determines which platforms users can access with this code",
                max_length=50,
                verbose_name="Access Scope",
            ),
        ),
    ]
