# Generated by Django 5.1.11 on 2025-07-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_accesscodegroup_scope"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_socratic_books_accessible",
        ),
        migrations.AddField(
            model_name="user",
            name="is_socratic_bots_accessible",
            field=models.BooleanField(
                default=False,
                help_text="Whether this user can access SocraticBots platform",
                verbose_name="SocraticBots Access",
            ),
        ),
        migrations.AlterField(
            model_name="accesscodegroup",
            name="scope",
            field=models.CharField(
                choices=[("DARE", "DARE Only"), ("DUAL", "DARE + SocraticBots")],
                default="DARE",
                help_text="Determines which platforms users can access with this code",
                max_length=50,
                verbose_name="Access Scope",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="auth_source",
            field=models.CharField(
                choices=[("DARE", "DARE"), ("SocraticBots", "SocraticBots")],
                default="DARE",
                help_text="Platform where the user was originally authenticated",
                max_length=50,
                verbose_name="Authentication Source",
            ),
        ),
    ]
