# Generated by Django 5.1.11 on 2025-08-08 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0022_add_selected_ids_to_conversation"),
        ("users", "0012_update_auth_source_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesscodegroup",
            name="model_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Model group applied to users who register with this access code group",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_code_groups",
                to="conversations.modelgroup",
            ),
        ),
    ]
