# Generated by Django 5.1.11 on 2025-08-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_accesscodegroup_model_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="model_group",
        ),
    ]
