# Generated by Django 5.1.13 on 2025-10-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_merge_0014_conflicts"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="industry",
            field=models.TextField(
                blank=True,
                help_text="User's industry, domain of study, or academic major",
                null=True,
                verbose_name="Industry/Major",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="purpose",
            field=models.TextField(
                blank=True,
                help_text="User's goals for using DARE",
                null=True,
                verbose_name="Goals of using DARE",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="referral_source",
            field=models.TextField(
                blank=True,
                help_text="Where did you hear about DARE?/What class were you assigned access to DARE?",
                null=True,
                verbose_name="Referral Source",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.TextField(
                blank=True,
                help_text="User's role, profession, or student status",
                null=True,
                verbose_name="Role/Profession/Student",
            ),
        ),
    ]
