# Generated by Django 5.1.12 on 2025-10-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_merge_0014_conflicts"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="billing_mode",
            field=models.CharField(
                choices=[
                    ("wallet", "Use Wallet Credits"),
                    ("own_api", "Use Own API Keys"),
                ],
                default="wallet",
                help_text="How the user pays for API usage: wallet credits or own API keys",
                max_length=20,
                verbose_name="Billing Mode",
            ),
        ),
    ]
