# Generated by Django 5.1.13 on 2025-10-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_user_industry_user_purpose_user_referral_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_onboarding_completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has completed the onboarding process",
                verbose_name="Onboarding Completed",
            ),
        ),
    ]
