# Generated by Django 5.1.13 on 2025-10-17 18:02

from django.db import migrations

def grandfather_existing_users(apps, schema_editor):
    User = apps.get_model('users', 'User')
    # Set all existing users to onboarding completed
    User.objects.all().update(is_onboarding_completed=True)



class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_add_onboarding_completed_field"),
    ]

    operations = [
        migrations.RunPython(grandfather_existing_users),
    ]
