# Generated by Django 5.1.12 on 2025-10-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_billing_mode'),
        ('users', '0018_grandfather_existing_users'),
    ]

    operations = [
    ]
