# Generated by Django 5.1.12 on 2025-11-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_merge_20251021_1743"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesscodegroup",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when this access code expires. Users with this code will be deactivated after this date. Leave blank for no expiration.",
                null=True,
                verbose_name="Expiration Date",
            ),
        ),
    ]
