# Generated by Django 5.1.12 on 2025-11-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_accesscodegroup_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscodegroup',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this access code group (e.g., class name, semester, purpose)', null=True, verbose_name='Notes'),
        ),
    ]
