# Generated by Django 5.1.12 on 2025-12-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_accesscodegroup_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_preset",
            field=models.CharField(
                blank=True,
                help_text="Identifier for preset avatar image",
                max_length=50,
                null=True,
                verbose_name="Avatar Preset",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_type",
            field=models.CharField(
                choices=[
                    ("initials", "Initials"),
                    ("preset", "Preset Avatar"),
                    ("custom", "Custom Upload"),
                ],
                default="initials",
                help_text="Type of avatar: initials, preset image, or custom upload",
                max_length=20,
                verbose_name="Avatar Type",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                help_text="URL for custom uploaded avatar image",
                null=True,
                verbose_name="Avatar URL",
            ),
        ),
    ]
