# Generated by Django 5.1.15 on 2026-01-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_add_avatar_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="storage_backend",
            field=models.IntegerField(
                choices=[(1, "Local FileSystem"), (2, "SyftBox Distributed Storage")],
                default=1,
                help_text="Preferred storage backend for new file uploads",
                verbose_name="Storage Backend",
            ),
        ),
    ]
