# Generated by Django 5.1.15 on 2026-02-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_set_superadmin_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscodegroup',
            name='default_role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('RESEARCHER', 'Researcher'), ('USER', 'User'), ('CREATOR', 'Creator'), ('SB_USER', 'SocraticBots User')], default='USER', help_text='Role assigned to users who register with this access code', max_length=20, verbose_name='Default Role'),
        ),
        migrations.AlterField(
            model_name='accesscodegroup',
            name='scope',
            field=models.CharField(choices=[('DARE', 'DARE Only'), ('DUAL', 'DARE + SocraticBots')], default='DARE', help_text='DEPRECATED: Use default_role instead. Platform access is now role-based.', max_length=50, verbose_name='Access Scope (Deprecated)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='platform_role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('RESEARCHER', 'Researcher'), ('USER', 'User'), ('CREATOR', 'Creator'), ('SB_USER', 'SocraticBots User')], default='USER', help_text="User's role across DARE and SocraticBots platforms", max_length=20, verbose_name='Platform Role'),
        ),
    ]
