# Generated by Django 5.1.15 on 2026-02-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_user_storage_backend"),
        ("users", "0026_alter_accesscodegroup_default_role_and_more"),
    ]

    operations = []
