# Generated by Django 5.1.15 on 2026-03-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_alter_accesscodegroup_default_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesscodegroup",
            name="default_role",
            field=models.CharField(
                choices=[
                    ("SUPERADMIN", "Super Admin"),
                    ("SUPERVISOR", "Supervisor"),
                    ("RESEARCHER", "Researcher"),
                    ("USER", "User"),
                    ("CREATOR", "Creator"),
                    ("SB_USER", "SocraticBots User"),
                ],
                default="USER",
                help_text="Role assigned to users who register with this access code. SUPERVISOR: DARE platform access + cross-user bot/agent management in SocraticBooks + creator access. RESEARCHER: DARE platform access + SocraticBooks creator (can create/manage books). USER: DARE platform access + SocraticBooks student/consumer (can read/interact with books). CREATOR: No DARE access + SocraticBooks creator (can create/manage books). SB_USER: No DARE access + SocraticBooks student/consumer only.",
                max_length=20,
                verbose_name="Default Role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="platform_role",
            field=models.CharField(
                choices=[
                    ("SUPERADMIN", "Super Admin"),
                    ("SUPERVISOR", "Supervisor"),
                    ("RESEARCHER", "Researcher"),
                    ("USER", "User"),
                    ("CREATOR", "Creator"),
                    ("SB_USER", "SocraticBots User"),
                ],
                default="USER",
                help_text="User's role across DARE and SocraticBots platforms. ADMIN: DARE admin access + SB creator + voice agent. RESEARCHER: DARE access + SB creator. USER: DARE access + SB student/consumer. CREATOR: No DARE + SB creator. SB_USER: No DARE + SB student/consumer only.",
                max_length=20,
                verbose_name="Platform Role",
            ),
        ),
    ]
