# Generated by Django 5.1.15 on 2026-04-02 14:33

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_alter_accesscodegroup_default_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="syftbox_access_token",
            field=core.fields.EncryptedCharField(
                blank=True,
                help_text="Latest Syftbox OAuth access token for this user",
                null=True,
                verbose_name="Syftbox Access Token",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="syftbox_refresh_token",
            field=core.fields.EncryptedCharField(
                blank=True,
                help_text="Latest Syftbox OAuth refresh token for this user",
                null=True,
                verbose_name="Syftbox Refresh Token",
            ),
        ),
    ]
