# Generated by Django 5.1.15 on 2026-04-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_alter_accesscodegroup_default_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="syftbox_access_token",
            field=models.TextField(
                blank=True,
                help_text="Latest Syftbox OAuth access token for this user",
                null=True,
                verbose_name="Syftbox Access Token",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="syftbox_refresh_token",
            field=models.TextField(
                blank=True,
                help_text="Latest Syftbox OAuth refresh token for this user",
                null=True,
                verbose_name="Syftbox Refresh Token",
            ),
        ),
    ]
