# Generated by Django 5.1.15 on 2026-04-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_accesscodegroup_group_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="billing_mode",
            field=models.CharField(
                choices=[
                    ("wallet", "Use Wallet Credits"),
                    ("own_api", "Use Own API Keys"),
                    ("litellm", "Use LiteLLM Proxy Key"),
                ],
                default="wallet",
                help_text="How the user pays for API usage: wallet credits or own API keys",
                max_length=20,
                verbose_name="Billing Mode",
            ),
        ),
    ]
