# Generated by Django 5.1.15 on 2026-05-21 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_alter_accesscodegroup_default_role_and_more"),
        ("users", "0032_multi_wallet"),
    ]

    operations = []
