# Generated by Django 5.1.8 on 2025-05-08 21:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=15,
                help_text="Transaction amount in USD",
                max_digits=15,
                verbose_name="Amount",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.00"),
                help_text="Wallet balance in USD",
                max_digits=15,
                verbose_name="Balance",
            ),
        ),
    ]
