# Generated by Django 5.1.8 on 2025-05-09 14:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_alter_transaction_amount_alter_wallet_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("5.00"),
                help_text="Wallet balance in USD",
                max_digits=15,
                verbose_name="Balance",
            ),
        ),
    ]
