# Generated by Django 5.1.6 on 2025-05-10 13:06

from django.db import migrations
from decimal import Decimal


def create_wallets_for_existing_users(apps, schema_editor):
    """
    Create a Wallet object for each existing User without a wallet.
    """
    User = apps.get_model('users', 'User')
    Wallet = apps.get_model('billing', 'Wallet')

    users_without_wallets = User.objects.filter(wallet__isnull=True)

    for user in users_without_wallets:
        Wallet.objects.create(
            user=user,
            balance=Decimal('5.00')
        )


def reverse_create_wallets(apps, schema_editor):
    """
    Reverse the migration by deleting wallets created for users.
    Note: This is a cautious reversal, only deleting wallets with default balance
    to avoid accidental data loss.
    """
    Wallet = apps.get_model('billing', 'Wallet')
    Wallet.objects.filter(balance=Decimal('5.00')).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_alter_wallet_balance"),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=create_wallets_for_existing_users,
            reverse_code=reverse_create_wallets,
        ),
    ]
