# Generated by Django 5.1.6 on 2025-05-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_auto_20250510_1306"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="input_tokens",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Number of input tokens used in the transaction",
                null=True,
                verbose_name="Input Tokens",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="output_tokens",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Number of output tokens used in the transaction",
                null=True,
                verbose_name="Output Tokens",
            ),
        ),
    ]
