# Generated by Django 5.1.8 on 2025-05-22 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_transaction_input_tokens_transaction_output_tokens"),
        ("conversations", "0012_llm_input_token_rate_per_million_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="llm",
            field=models.ForeignKey(
                blank=True,
                help_text="Model used in the transaction",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="conversations.llm",
                verbose_name="Model",
            ),
        ),
    ]
