# Generated by Django 5.1.11 on 2025-10-03 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_alter_transaction_amount"),
        ("conversations", "0025_conversation_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="llm_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the LLM model used (stored for historical reference)",
                max_length=255,
                null=True,
                verbose_name="Model Name",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="llm",
            field=models.ForeignKey(
                blank=True,
                help_text="Model used in the transaction",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="conversations.llm",
                verbose_name="Model",
            ),
        ),
    ]
