# Generated by Django 5.1.11 on 2025-10-03 13:07

from django.db import migrations


def populate_llm_names(apps, schema_editor):
    """
    Populate llm_name field for all existing transactions that have an LLM assigned.
    """
    Transaction = apps.get_model('billing', 'Transaction')
    LLM = apps.get_model('conversations', 'LLM')

    # Get all transactions with an LLM but no llm_name
    transactions_to_update = Transaction.objects.filter(
        llm__isnull=False,
        llm_name__isnull=True
    ).select_related('llm')

    # Update each transaction with the LLM name
    for transaction in transactions_to_update:
        transaction.llm_name = transaction.llm.name

    # Bulk update for efficiency
    if transactions_to_update:
        Transaction.objects.bulk_update(transactions_to_update, ['llm_name'], batch_size=500)


def reverse_populate_llm_names(apps, schema_editor):
    """
    Reverse migration - clear llm_name field
    """
    Transaction = apps.get_model('billing', 'Transaction')
    Transaction.objects.update(llm_name=None)


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_add_llm_name_to_transaction"),
        ("conversations", "0024_conversation_learning_metadata_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_llm_names, reverse_populate_llm_names),
    ]
