# Generated by Django 5.1.12 on 2025-10-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_populate_existing_llm_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='billing_mode',
            field=models.CharField(choices=[('wallet', 'Use Wallet Credits'), ('own_api', 'Use Own API Keys')], default='wallet', help_text='Billing mode used for this transaction: wallet or own API keys', max_length=20, verbose_name='Billing Mode'),
        ),
    ]
