# Generated by Django 5.1.12 on 2025-11-04 13:42

import re
from django.db import migrations, connection


def prefill_transaction_platforms(apps, schema_editor):
    """
    Prefill the platform field in transactions by extracting message IDs
    from transaction messages and looking up the conversation source.
    """
    Transaction = apps.get_model('billing', 'Transaction')

    # Pattern to extract message ID from transaction message
    # Examples: "Message 123: ...", "Message 94: ..."
    message_pattern = re.compile(r'Message (\d+):', re.IGNORECASE)

    # Statistics
    stats = {
        'total': 0,
        'updated_to_socratic': 0,
        'already_correct': 0,
        'message_not_found': 0,
        'no_pattern_match': 0,
        'workflow_based': 0,
    }

    # Get all transactions
    transactions = Transaction.objects.all()
    stats['total'] = transactions.count()

    for txn in transactions:
        # Workflow transactions are DARE-only
        if 'Workflow' in txn.message:
            stats['workflow_based'] += 1
            continue

        # Image generation is DARE-only - skip updating
        if 'Image Generation' in txn.message:
            continue

        # Try to extract message ID
        match = message_pattern.search(txn.message)
        if not match:
            stats['no_pattern_match'] += 1
            continue

        message_id = int(match.group(1))

        # Look up the message and get the conversation source using raw SQL
        try:
            with connection.cursor() as cursor:
                cursor.execute("""
                    SELECT c.source
                    FROM conversations_message m
                    JOIN conversations_conversation c ON m.conversation_id = c.id
                    WHERE m.id = %s AND m.is_deleted = 0
                """, [message_id])
                result = cursor.fetchone()

            if not result:
                stats['message_not_found'] += 1
                continue

            conversation_source = result[0]

            # Update transaction platform if different
            if txn.platform != conversation_source:
                txn.platform = conversation_source
                txn.save(update_fields=['platform'])
                if conversation_source == 'SocraticBots':
                    stats['updated_to_socratic'] += 1
            else:
                stats['already_correct'] += 1

        except Exception as e:
            stats['message_not_found'] += 1
            continue

    # Print summary
    print(f"\n=== Transaction Platform Prefill Summary ===")
    print(f"Total transactions: {stats['total']}")
    print(f"  - Already correct: {stats['already_correct']}")
    print(f"  - Updated to SocraticBots: {stats['updated_to_socratic']}")
    print(f"  - Workflow-based (skipped): {stats['workflow_based']}")
    print(f"  - Message not found: {stats['message_not_found']}")
    print(f"  - No pattern match: {stats['no_pattern_match']}")
    print(f"============================================\n")


def reverse_prefill(apps, schema_editor):
    """
    Reverse migration - reset all SocraticBots transactions back to DARE default.
    Note: This is a lossy operation and should only be used if absolutely necessary.
    """
    Transaction = apps.get_model('billing', 'Transaction')

    # Reset all SocraticBots transactions to DARE
    updated_count = Transaction.objects.filter(platform='SocraticBots').update(platform='DARE')
    print(f"Reset {updated_count} transactions from SocraticBots to DARE")


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0011_add_platform_to_transaction"),
        ("conversations", "0025_conversation_source"),  # Ensure conversation.source field exists
    ]

    operations = [
        migrations.RunPython(prefill_transaction_platforms, reverse_prefill),
    ]
