# Generated by Django 5.1.15 on 2026-04-28 12:44

import core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0015_seed_and_backfill"),
        ("users", "0032_multi_wallet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupwallet",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="systemrefillpolicy",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="billing_mode",
            field=models.CharField(
                choices=[
                    ("wallet", "Use Wallet Credits"),
                    ("own_api", "Use Own API Keys"),
                    ("litellm", "Use LiteLLM Proxy Key"),
                ],
                default="wallet",
                help_text="Billing mode used for this transaction: wallet or own API keys",
                max_length=20,
                verbose_name="Billing Mode",
            ),
        ),
        migrations.AlterField(
            model_name="userrefilloverride",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="BYOKeyFeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, users may add and select their own provider API keys (BYO) as the active wallet.",
                        verbose_name="BYO Key Enabled",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Last admin to toggle this flag.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "BYO Key Feature Flag",
                "verbose_name_plural": "BYO Key Feature Flag",
            },
        ),
        migrations.CreateModel(
            name="UserWalletPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_wallet_type",
                    models.CharField(
                        choices=[
                            ("DARE", "DARE Wallet"),
                            ("BYO", "BYO Key"),
                            ("LITELLM", "LiteLLM Key"),
                        ],
                        default="DARE",
                        max_length=16,
                        verbose_name="Active Wallet Type",
                    ),
                ),
                (
                    "active_wallet_ref_id",
                    models.CharField(
                        blank=True,
                        help_text="Identifier of the active wallet within its type table — UserProviderAPIKey.id (BYO) or LiteLLMKey.id (LITELLM). Null for DARE.",
                        max_length=64,
                        null=True,
                        verbose_name="Active Wallet Reference",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Wallet Preference",
                "verbose_name_plural": "User Wallet Preferences",
            },
        ),
        migrations.CreateModel(
            name="LiteLLMKey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable name to disambiguate keys (e.g. 'Personal' or 'PHIL 101 - Spring 2026').",
                        max_length=128,
                        verbose_name="Label",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        help_text="LiteLLM proxy URL — e.g. https://litellm-proxy.example.com.",
                        verbose_name="Base URL",
                    ),
                ),
                (
                    "api_key",
                    core.fields.EncryptedCharField(
                        help_text="LiteLLM proxy API key (stored encrypted using AES-256).",
                        max_length=500,
                        verbose_name="API Key",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("USER", "User self-served"),
                            ("ADMIN_USER", "Admin issued to user"),
                            ("ADMIN_GROUP", "Admin issued to group"),
                        ],
                        help_text="Where the key originated — user self-served, admin-issued to a user, or admin-issued to a group.",
                        max_length=16,
                        verbose_name="Source",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional hard expiry. Past expiry hides the key from the user's wallet list.",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when source=ADMIN_USER. The user the admin assigned this key to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="litellm_keys_assigned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned User",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this record (admin or self).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when source=USER. The user who self-served this key.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="litellm_keys_owned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner User",
                    ),
                ),
                (
                    "source_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when source=ADMIN_GROUP. The cohort whose members all have access to this key.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="litellm_keys",
                        to="users.accesscodegroup",
                        verbose_name="Source Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "LiteLLM Key",
                "verbose_name_plural": "LiteLLM Keys",
                "indexes": [
                    models.Index(
                        fields=["owner_user"], name="billing_lit_owner_u_6f1350_idx"
                    ),
                    models.Index(
                        fields=["assigned_user"], name="billing_lit_assigne_e66dc7_idx"
                    ),
                    models.Index(
                        fields=["source_group"], name="billing_lit_source__6cffc2_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source", "USER"),
                                ("owner_user__isnull", False),
                                ("assigned_user__isnull", True),
                                ("source_group__isnull", True),
                            ),
                            models.Q(
                                ("source", "ADMIN_USER"),
                                ("assigned_user__isnull", False),
                                ("owner_user__isnull", True),
                                ("source_group__isnull", True),
                            ),
                            models.Q(
                                ("source", "ADMIN_GROUP"),
                                ("source_group__isnull", False),
                                ("owner_user__isnull", True),
                                ("assigned_user__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="litellm_source_owner_consistency",
                    )
                ],
            },
        ),
    ]
