# Generated by Django 5.1.15 on 2026-04-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0015_seed_and_backfill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupwallet",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="systemrefillpolicy",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userrefilloverride",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
