# Generated by Django 5.1.15 on 2026-04-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_alter_groupwallet_id_alter_systemrefillpolicy_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Usage Dashboard',
                'verbose_name_plural': 'Usage Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.transaction',),
        ),
    ]
