# Generated by Django 5.1.12 on 2026-05-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_add_usage_dashboard_proxy'),
        ('billing', '0017_transaction_bot_attribution'),
    ]

    operations = [
    ]
