# Generated by Django 5.1.12 on 2026-05-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0019_migrate_byo_flag_to_feature_flags"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BYOKeyFeatureFlag",
        ),
    ]
