# Generated by Django 5.1.12 on 2025-11-07 14:23

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prompts', '0003_prompt_parent'),
        ('conversations', '0001_initial'),
        ('files', '0011_add_composite_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Name of the agent.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the agent.')),
                ('max_tokens', models.PositiveIntegerField(default=2048, help_text='Maximum tokens for LLM response')),
                ('temperature', models.FloatField(default=0.7, help_text='Temperature setting for the LLM', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('max_context_snippets', models.PositiveIntegerField(default=4, help_text='Maximum number of context snippets to retrieve')),
                ('document_similarity_threshold', models.FloatField(default=0.2, help_text='Similarity threshold for document retrieval')),
                ('enable_web_search', models.BooleanField(default=False, help_text="If true, enable web search for this agent's LLM")),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number of the agent. Increments when cloned.')),
                ('content_files', models.ManyToManyField(blank=True, help_text='Files to be processed with full content', related_name='agent_content', to='files.file')),
                ('embedding_files', models.ManyToManyField(blank=True, help_text='Files to be processed using embeddings/vector search', related_name='agent_embeddings', to='files.file')),
                ('llm', models.ForeignKey(blank=True, help_text='Language model for this agent', null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversations.llm')),
                ('parent', models.ForeignKey(blank=True, help_text='Original agent this was cloned from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='agents.agent')),
                ('prompt', models.ForeignKey(help_text='Prompt template for this agent', on_delete=django.db.models.deletion.PROTECT, to='prompts.prompt')),
                ('user', models.ForeignKey(help_text='User who owns this agent.', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AgentNodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Override agent name for this workflow node', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Override agent description for this workflow node')),
                ('agent_number', models.PositiveIntegerField(help_text='Agent order in workflow')),
                ('max_tokens', models.PositiveIntegerField(default=2048, help_text='Maximum tokens for LLM response')),
                ('temperature', models.FloatField(default=0.7, help_text='Temperature setting for the LLM', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('max_context_snippets', models.PositiveIntegerField(default=4, help_text='Maximum number of context snippets to retrieve')),
                ('document_similarity_threshold', models.FloatField(default=0.2, help_text='Similarity threshold for document retrieval')),
                ('use_previous_agent_files', models.BooleanField(default=False, help_text='Inherit files from previous agent')),
                ('use_previous_agent_embeddings', models.BooleanField(default=False, help_text='Inherit embeddings from previous agent')),
                ('text_input', models.TextField(blank=True, default='', help_text='Optional text input to be passed directly to the LLM')),
                ('use_structured_output_node', models.BooleanField(default=False, help_text='If true, this agent uses a separate StructuredOutputNode for routing')),
                ('enable_web_search', models.BooleanField(default=False, help_text="If true, enable web search for this agent's LLM")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, help_text='Agent to use as base configuration', null=True, on_delete=django.db.models.deletion.PROTECT, to='agents.agent')),
                ('content_files', models.ManyToManyField(blank=True, help_text='Files to be processed with full content', related_name='agent_node_content', to='files.file')),
                ('embedding_files', models.ManyToManyField(blank=True, help_text='Files to be processed using embeddings/vector search', related_name='agent_node_embeddings', to='files.file')),
                ('llm', models.ForeignKey(blank=True, help_text='Language model for this agent', null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversations.llm')),
                ('prompt', models.ForeignKey(blank=True, help_text='Prompt template for this agent', null=True, on_delete=django.db.models.deletion.PROTECT, to='prompts.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateAgentNodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Override agent name for this workflow node', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Override agent description for this workflow node')),
                ('agent_number', models.PositiveIntegerField(help_text='Agent order in workflow')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(help_text='Agent template to use', on_delete=django.db.models.deletion.PROTECT, to='agents.agent')),
            ],
        ),
    ]
