# Generated by Django 5.1.6 on 2025-03-08 00:38

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0003_seed_default_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the Language Model.", max_length=255
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Technical identifier used in API calls (e.g., claude-3.5-sonnet-20240307).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the language model capabilities.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "LLMs",
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "conversation_id",
                    models.CharField(
                        help_text="Unique conversation ID.", max_length=10, unique=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Title of the conversation.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this conversation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "sender_type",
                    models.IntegerField(
                        choices=[(1, "Player"), (2, "AI Assistant")],
                        help_text="Type of sender (User or AI).",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        blank=True,
                        help_text="Name or identifier of the sender.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("message", models.TextField(help_text="Content of the message.")),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="Corresponding conversation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Files referenced in this message",
                        related_name="chat_messages",
                        to="files.file",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
