# Generated by Django 5.1.6 on 2025-03-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llm",
            name="provider",
            field=models.CharField(
                choices=[("openai", "Openai"), ("claude", "Claude")],
                default="openai",
                help_text="Provider of the LLM (e.g., OpenAI, Claude).",
                max_length=20,
            ),
        ),
    ]
