# Generated by Django 5.1.6 on 2025-03-08 07:53

from django.db import migrations

def seed_llm_models(apps, schema_editor):
    """Seed initial LLM models for OpenAI and Claude providers."""
    LLM = apps.get_model("conversations", "LLM")
    
    # https://docs.anthropic.com/en/api/getting-started
    # https://platform.openai.com/docs/quickstart

    llm_data = [
        # OpenAI Models
        {"name": "GPT-4o Mini", "identifier": "gpt-4o-mini", "provider": "openai", "description": "OpenAI's 4o mini model."},
        {"name": "GPT-3.5 Turbo", "identifier": "gpt-3.5-turbo", "provider": "openai", "description": "Optimized version of GPT-3.5."},

        # Claude Models
        {"name": "Claude 3 Sonnet", "identifier": "claude-3-7-sonnet-20250219", "provider": "claude", "description": "Anthropic's Claude 3 Sonnet model."},
    ]

    for llm in llm_data:
        LLM.objects.get_or_create(
            identifier=llm["identifier"],
            defaults={
                "name": llm["name"],
                "provider": llm["provider"],
                "description": llm["description"],
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0002_llm_provider"),
    ]

    operations = [
        migrations.RunPython(seed_llm_models),
    ]
