# Generated by Django 5.1.6 on 2025-04-20 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0007_snippet"),
        ("prompts", "0003_prompt_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="document_similarity_threshold",
            field=models.FloatField(
                default=0.2, help_text="Similarity threshold for document retrieval."
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="max_context_snippets",
            field=models.PositiveIntegerField(
                default=4, help_text="Maximum number of context snippets to retrieve."
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="max_tokens",
            field=models.PositiveIntegerField(
                default=2048, help_text="Maximum tokens for LLM responses."
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="prompt",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated prompt for this conversation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="prompts.prompt",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="temperature",
            field=models.FloatField(
                default=0.7, help_text="Temperature setting for the LLM."
            ),
        ),
    ]
