# Generated by Django 5.1.8 on 2025-04-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0008_conversation_document_similarity_threshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_disliked",
            field=models.BooleanField(
                default=False,
                help_text="Whether this message has been disliked by the user.",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_liked",
            field=models.BooleanField(
                default=False,
                help_text="Whether this message has been liked by the user.",
            ),
        ),
    ]
