# Generated by Django 5.1.6 on 2025-05-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0009_message_is_disliked_message_is_liked"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_edited",
            field=models.BooleanField(
                default=False,
                help_text="Whether this message has been edited by the user (applies to user messages only).",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_regenerated",
            field=models.BooleanField(
                default=False,
                help_text="Whether this message has been regenerated (applies to AI messages only).",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="original_message",
            field=models.TextField(
                blank=True,
                help_text="Original content of the message before editing or regeneration.",
                null=True,
            ),
        ),
    ]
