# Generated by Django 5.1.8 on 2025-05-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0010_message_is_edited_message_is_regenerated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="input_tokens",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of input tokens used in the LLM request.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="output_tokens",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of output tokens generated by the LLM.",
                null=True,
            ),
        ),
    ]
