# Generated by Django 5.1.8 on 2025-05-07 18:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0011_message_input_tokens_message_output_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="llm",
            name="input_token_rate_per_million",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Cost per million input tokens in USD (e.g., 3.00 for $3 per 1M tokens).",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="llm",
            name="output_token_rate_per_million",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Cost per million output tokens in USD (e.g., 15.00 for $15 per 1M tokens).",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
