# Generated by Django 5.1.6 on 2025-05-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0012_llm_input_token_rate_per_million_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="history_limit",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Maximum number of messages to include in conversation history.",
            ),
        ),
    ]
