# Generated by Django 5.1.8 on 2025-06-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0013_conversation_history_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Sort order for drag-and-drop functionality. Higher values appear later.",
            ),
        ),
    ]
