# Generated by Django 5.1.11 on 2025-06-14 06:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0016_alter_conversation_history_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=Decimal("0.000000"),
                help_text="Cost of this message in USD based on token usage and LLM pricing.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
