# Generated by Django 5.1.11 on 2025-07-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0019_remove_message_dislike_feedback_and_more'),
    ]

    operations = [
    ]
