# Generated by Django 5.1.11 on 2025-07-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0020_auto_20250718_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llm',
            name='provider',
            field=models.CharField(choices=[('openai', 'Openai'), ('claude', 'Claude'), ('gemini', 'Gemini'), ('llama', 'Llama')], default='openai', help_text='Provider of the LLM (e.g., OpenAI, Claude).', max_length=20),
        ),
        migrations.CreateModel(
            name='ModelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the model group (e.g., 'Basic', 'Premium', 'Enterprise').", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the model group and its capabilities.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model group is currently active and can be assigned to users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_models', models.ManyToManyField(help_text='LLM models that users in this group can access.', related_name='model_groups', to='conversations.llm')),
            ],
            options={
                'verbose_name': 'Model Group',
                'verbose_name_plural': 'Model Groups',
                'ordering': ['name'],
            },
        ),
    ]
