# Generated by Django 5.1.11 on 2025-07-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0021_alter_llm_provider_modelgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="selected_embedding_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of selected embedding file IDs for this conversation.",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="selected_file_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of selected file IDs for this conversation.",
            ),
        ),
    ]
