# Generated by Django 5.1.11 on 2025-08-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0022_add_selected_ids_to_conversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="conversation_id",
            field=models.CharField(
                help_text="Unique conversation ID.", max_length=50, unique=True
            ),
        ),
    ]
