# Generated by Django 5.1.11 on 2025-08-15 14:21

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0023_alter_conversation_conversation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="learning_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Learning-specific metadata including goals, tracking settings, and educational context.",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="learning_progress_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Learning progress data associated with this message, such as assessment triggers and educational metadata.",
            ),
        ),
        migrations.CreateModel(
            name="LearningProgressAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "content",
                    models.TextField(
                        help_text="AI-generated progress assessment content (Markdown formatted)."
                    ),
                ),
                (
                    "learning_goals",
                    models.TextField(
                        blank=True,
                        help_text="Learning goals that were used for this assessment.",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata including assessment parameters, AI model used, etc.",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="The conversation this assessment belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_assessments",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "last_message",
                    models.ForeignKey(
                        blank=True,
                        help_text="The message that triggered this assessment (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_assessments",
                        to="conversations.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Progress Assessment",
                "verbose_name_plural": "Learning Progress Assessments",
                "ordering": ["-created_at"],
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
