# Generated by Django 5.1.11 on 2025-08-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0024_conversation_learning_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="source",
            field=models.CharField(
                choices=[("DARE", "DARE"), ("SocraticBots", "SocraticBots")],
                default="DARE",
                help_text="Platform source where the conversation was created (DARE or SocraticBots).",
                max_length=20,
            ),
        ),
    ]
