# Generated by Django 5.1.12 on 2025-09-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0025_conversation_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="llm",
            name="supports_vision",
            field=models.BooleanField(
                default=True,
                help_text="Whether the model supports vision/image analysis (e.g., GPT-4V, Claude 3+, Gemini Pro Vision).",
            ),
        ),
    ]
