# Generated by Django 5.1.12 on 2025-10-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0027_add_web_search_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageWithFeedback',
            fields=[
            ],
            options={
                'verbose_name': 'Message with Feedback',
                'verbose_name_plural': 'Messages with Feedback',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('conversations.message',),
        ),
    ]
