# Generated by Django 5.1.12 on 2025-10-17 13:47

import core.fields
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0028_messagewithfeedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "Openai"),
                            ("claude", "Claude"),
                            ("gemini", "Gemini"),
                            ("llama", "Llama"),
                        ],
                        help_text="LLM provider (e.g., OpenAI, Anthropic, Google, Meta)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "api_key",
                    core.fields.EncryptedCharField(
                        help_text="API key for this provider (stored encrypted using AES-256)",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider API Key",
                "verbose_name_plural": "Provider API Keys",
                "ordering": ["provider"],
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
