# Generated by Django 5.1.12 on 2025-10-21 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0029_providerapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='image_generation_enabled',
            field=models.BooleanField(default=False, help_text='Enable AI image generation for this conversation.'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='selected_media_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of selected media file IDs for this conversation.'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='selected_model',
            field=models.ForeignKey(blank=True, help_text='Selected LLM model for this conversation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_using_model', to='conversations.llm'),
        ),
    ]
