# Generated by Django 5.1.12 on 2025-10-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0030_conversation_image_generation_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm',
            name='is_image_generator',
            field=models.BooleanField(default=False, help_text='Whether the model is an image generation model (e.g., DALL-E).'),
        ),
    ]
