# Generated by Django 5.1.13 on 2025-10-29 00:26
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0031_llm_is_image_generator'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='feedback_source',
            field=models.CharField(
                blank=True,
                choices=[
                    ('thumbs', 'Thumbs Click'),
                    ('manual', 'Manual Feedback Button'),
                    ('auto', 'Automatic Prompt')
                ],
                default='thumbs',
                help_text='Source that triggered the feedback submission',
                max_length=10,
                null=True
            ),
        ),
    ]
