# Generated by Django 5.1.12 on 2025-10-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0031_llm_is_image_generator"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="bot_id",
            field=models.IntegerField(
                blank=True,
                help_text="Associated Socratic Bot ID (only populated for SocraticBots source).",
                null=True,
            ),
        ),
    ]
