# Generated by Django 5.1.13 on 2025-10-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0032_message_feedback_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="feedback_auto_prompt_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of times auto-feedback prompt has been shown for this conversation",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="feedback_last_prompt_message_count",
            field=models.IntegerField(
                default=0, help_text="Message count when feedback prompt was last shown"
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="feedback_last_prompt_timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when feedback prompt was last shown",
                null=True,
            ),
        ),
    ]
