# Generated by Django 5.1.12 on 2025-11-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0033_add_feedback_auto_prompt_tracking"),
        ("conversations", "0034_make_user_nullable_add_session_id"),
    ]

    operations = []
