# Generated by Django 5.1.12 on 2025-11-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0036_add_composite_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm',
            name='base_url',
            field=models.URLField(blank=True, help_text='Custom base URL for the API endpoint (required for CUSTOM provider, e.g., https://litellm-dev.pace.gatech.edu:4000/v1).', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='llm',
            name='provider',
            field=models.CharField(choices=[('openai', 'Openai'), ('claude', 'Claude'), ('gemini', 'Gemini'), ('llama', 'Llama'), ('custom', 'Custom')], default='openai', help_text='Provider of the LLM (e.g., OpenAI, Claude).', max_length=20),
        ),
        migrations.AlterField(
            model_name='providerapikey',
            name='provider',
            field=models.CharField(choices=[('openai', 'Openai'), ('claude', 'Claude'), ('gemini', 'Gemini'), ('llama', 'Llama'), ('custom', 'Custom')], help_text='LLM provider (e.g., OpenAI, Anthropic, Google, Meta)', max_length=20, unique=True),
        ),
    ]
