# Generated by Django 5.1.12 on 2025-12-04 04:26

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0037_llm_base_url_alter_llm_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('artifact_type', models.CharField(choices=[('document', 'Document'), ('code', 'Code'), ('diagram', 'Diagram')], default='document', help_text='Type of artifact (document, code, diagram).', max_length=20)),
                ('title', models.CharField(help_text='Title of the artifact.', max_length=500)),
                ('language', models.CharField(blank=True, help_text='Programming language for code artifacts.', max_length=50, null=True)),
                ('outline', models.TextField(blank=True, default='', help_text='Structured outline of the artifact sections.')),
                ('content', models.TextField(blank=True, default='', help_text='Generated content of the artifact.')),
                ('estimated_sections', models.PositiveIntegerField(default=10, help_text='Estimated number of sections in the artifact.')),
                ('current_section', models.PositiveIntegerField(default=0, help_text='Current section being generated (0 = not started).')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('generating', 'Generating'), ('paused', 'Paused'), ('completed', 'Completed'), ('error', 'Error')], default='planning', help_text='Current status of artifact generation.', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (LLM used, token counts, etc.).')),
                ('conversation', models.ForeignKey(help_text='The conversation this artifact belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='conversations.conversation')),
                ('message', models.ForeignKey(blank=True, help_text='The AI message associated with this artifact.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='conversations.message')),
            ],
            options={
                'verbose_name': 'Artifact',
                'verbose_name_plural': 'Artifacts',
                'ordering': ['-created_at'],
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content_snapshot', models.TextField(help_text='Content snapshot at this checkpoint.')),
                ('current_section', models.PositiveIntegerField(help_text='Section number at this checkpoint.')),
                ('iteration_count', models.PositiveIntegerField(default=0, help_text='Number of generation iterations completed.')),
                ('state_data', models.JSONField(default=dict, help_text='Serialized state data for resuming generation.')),
                ('artifact', models.ForeignKey(help_text='The artifact this checkpoint belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='conversations.artifact')),
            ],
            options={
                'verbose_name': 'Artifact Checkpoint',
                'verbose_name_plural': 'Artifact Checkpoints',
                'ordering': ['-created_at'],
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['conversation', 'status'], name='artifact_conv_status_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactcheckpoint',
            index=models.Index(fields=['artifact', 'created_at'], name='checkpoint_artifact_idx'),
        ),
    ]
