# Generated by Django 5.1.12 on 2025-12-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0038_add_artifact_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='artifacts_enabled',
            field=models.BooleanField(default=False, help_text='Enable artifact generation for long-form content.'),
        ),
    ]
