# Generated by Django 5.1.12 on 2025-12-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0039_add_artifacts_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version number, incremented on each modification.'),
        ),
    ]
