# Generated by Django 5.1.12 on 2025-12-08 14:35

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0040_artifact_version_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="parent_artifact",
            field=models.ForeignKey(
                blank=True,
                help_text="The previous version this artifact was derived from.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_versions",
                to="conversations.artifact",
            ),
        ),
        migrations.CreateModel(
            name="ArtifactGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "base_title",
                    models.CharField(
                        help_text="Original title of the artifact (from first version).",
                        max_length=500,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="The conversation this artifact group belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact_groups",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "latest_version",
                    models.OneToOneField(
                        blank=True,
                        help_text="The most recent version of this artifact.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="is_latest_for",
                        to="conversations.artifact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artifact Group",
                "verbose_name_plural": "Artifact Groups",
                "ordering": ["-created_at"],
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="artifact",
            name="artifact_group",
            field=models.ForeignKey(
                blank=True,
                help_text="The group containing all versions of this artifact.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="conversations.artifactgroup",
            ),
        ),
    ]
