# Generated by Django 5.1 on 2025-12-08

from django.db import migrations


def seed_additional_llm_models(apps, schema_editor):
    """
    Seed additional LLM models from staging/prod environment.
    Uses get_or_create to avoid duplicating models that already exist.
    """
    LLM = apps.get_model("conversations", "LLM")

    # LLM data from staging/prod environment
    # Skipping: o1, o3-mini, claude-3-7-sonnet-latest per requirements
    llm_data = [
        # OpenAI Models - Image Generators
        {
            "name": "DALL-E 3",
            "identifier": "dall-e-3",
            "provider": "openai",
            "is_image_generator": True,
            "supports_vision": False,
        },
        {
            "name": "DALL-E 2",
            "identifier": "dall-e-2",
            "provider": "openai",
            "is_image_generator": True,
            "supports_vision": False,
        },
        # Claude Models
        {
            "name": "Claude Opus 4.5",
            "identifier": "claude-opus-4-5-20251101",
            "provider": "claude",
            "is_image_generator": False,
            "supports_vision": True,
        },
        {
            "name": "Claude Sonnet 4.5 (Latest Flagship)",
            "identifier": "claude-sonnet-4-5-20250929",
            "provider": "claude",
            "is_image_generator": False,
            "supports_vision": True,
        },
        {
            "name": "Claude Sonnet 4",
            "identifier": "claude-sonnet-4-20250514",
            "provider": "claude",
            "is_image_generator": False,
            "supports_vision": True,
        },
        {
            "name": "Claude Haiku 4.5",
            "identifier": "claude-haiku-4-5-20251001",
            "provider": "claude",
            "is_image_generator": False,
            "supports_vision": True,
        },
        # Gemini Models
        {
            "name": "Gemini 3 Pro (Latest Flagship)",
            "identifier": "gemini-3-pro-preview",
            "provider": "gemini",
            "is_image_generator": False,
            "supports_vision": True,
        },
        {
            "name": "Gemini 2.5 Flash Lite",
            "identifier": "gemini-2.5-flash-lite",
            "provider": "gemini",
            "is_image_generator": False,
            "supports_vision": True,
        },
        {
            "name": "Gemini 2.5 Flash",
            "identifier": "gemini-2.5-flash",
            "provider": "gemini",
            "is_image_generator": False,
            "supports_vision": True,
        },
        # OpenAI GPT Models
        {
            "name": "GPT 5.1 (Latest Flagship)",
            "identifier": "gpt-5.1-2025-11-13",
            "provider": "openai",
            "is_image_generator": False,
            "supports_vision": True,
        },
        {
            "name": "GPT-5",
            "identifier": "gpt-5",
            "provider": "openai",
            "is_image_generator": False,
            "supports_vision": True,
        },
        {
            "name": "GPT-4o",
            "identifier": "gpt-4o",
            "provider": "openai",
            "is_image_generator": False,
            "supports_vision": True,
        },
        {
            "name": "GPT-4.1 mini (Cost-Optimized)",
            "identifier": "gpt-4.1-mini",
            "provider": "openai",
            "is_image_generator": False,
            "supports_vision": True,
        },
        {
            "name": "GPT-4.1",
            "identifier": "gpt-4.1",
            "provider": "openai",
            "is_image_generator": False,
            "supports_vision": True,
        },
        {
            "name": "GPT-4o Mini (Cost-Optimized)",
            "identifier": "gpt-4o-mini",
            "provider": "openai",
            "is_image_generator": False,
            "supports_vision": True,
        },
    ]

    created_count = 0
    skipped_count = 0

    for llm in llm_data:
        _, created = LLM.objects.get_or_create(
            identifier=llm["identifier"],
            defaults={
                "name": llm["name"],
                "provider": llm["provider"],
                "is_image_generator": llm.get("is_image_generator", False),
                "supports_vision": llm.get("supports_vision", True),
            },
        )
        if created:
            created_count += 1
        else:
            skipped_count += 1

    print(f"\nLLM Seed Migration: Created {created_count}, Skipped {skipped_count} (already exist)\n")


def reverse_seed(apps, schema_editor):
    """
    Reverse migration - remove the seeded LLMs.
    Only removes LLMs that were added by this migration.
    """
    LLM = apps.get_model("conversations", "LLM")

    identifiers_to_remove = [
        "dall-e-3",
        "dall-e-2",
        "claude-opus-4-5-20251101",
        "claude-sonnet-4-5-20250929",
        "claude-sonnet-4-20250514",
        "claude-haiku-4-5-20251001",
        "gemini-3-pro-preview",
        "gemini-2.5-flash-lite",
        "gemini-2.5-flash",
        "gpt-5.1-2025-11-13",
        "gpt-5",
        "gpt-4o",
        "gpt-4.1-mini",
        "gpt-4.1",
        "gpt-4o-mini",
    ]

    # Only delete if not referenced by any conversations or messages
    for identifier in identifiers_to_remove:
        try:
            llm = LLM.objects.get(identifier=identifier)
            # Check if LLM is in use before deleting
            if not llm.conversations_using_model.exists() and not llm.messages.exists():
                llm.delete()
        except LLM.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0041_add_artifact_versioning"),
    ]

    operations = [
        migrations.RunPython(seed_additional_llm_models, reverse_seed),
    ]
