# Generated by Django 5.1.12 on 2025-12-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0042_seed_additional_llm_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='audio_transcription_enabled',
            field=models.BooleanField(default=False, help_text='Enable audio transcription for this conversation.'),
        ),
    ]
