# Generated by Django 5.1.12 on 2025-12-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0043_add_audio_transcription_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm',
            name='is_audio_transcriber',
            field=models.BooleanField(default=False, help_text='Whether the model supports audio transcription (e.g., Whisper, Gemini).'),
        ),
    ]
