# Generated by Django 5.1 on 2025-12-17

from django.db import migrations


def seed_whisper_model(apps, schema_editor):
    """
    Seed Whisper-1 audio transcription model.
    Uses get_or_create to avoid duplicating if it already exists.
    """
    LLM = apps.get_model("conversations", "LLM")

    # Whisper-1 model data
    # Pricing: $0.006 per minute of audio
    whisper_data = {
        "name": "Whisper-1",
        "identifier": "whisper-1",
        "provider": "openai",
        "description": "OpenAI's speech-to-text transcription model. Supports 99+ languages with high accuracy.",
        "is_reasoning": False,
        "is_image_generator": False,
        "is_audio_transcriber": True,
        "supports_vision": False,
        # Whisper pricing is per minute, but we'll store as token rates for consistency
        # $0.006 per minute = $0.0001 per second
        # We'll use a nominal token rate since transcription isn't token-based
        "input_token_rate_per_million": 6.0,  # Approximate equivalent for tracking
        "output_token_rate_per_million": 0.0,  # No output tokens for transcription
    }

    llm, created = LLM.objects.get_or_create(
        identifier=whisper_data["identifier"],
        defaults={
            "name": whisper_data["name"],
            "provider": whisper_data["provider"],
            "description": whisper_data["description"],
            "is_reasoning": whisper_data["is_reasoning"],
            "is_image_generator": whisper_data["is_image_generator"],
            "is_audio_transcriber": whisper_data["is_audio_transcriber"],
            "supports_vision": whisper_data.get("supports_vision", False),
            "input_token_rate_per_million": whisper_data["input_token_rate_per_million"],
            "output_token_rate_per_million": whisper_data["output_token_rate_per_million"],
        },
    )

    if created:
        print(f"\nWhisper Seed Migration: Created {whisper_data['name']} model\n")
    else:
        print(f"\nWhisper Seed Migration: {whisper_data['name']} model already exists (skipped)\n")


def reverse_seed(apps, schema_editor):
    """
    Reverse migration - remove the Whisper-1 model.
    Only removes if it's not referenced by any conversations or messages.
    """
    LLM = apps.get_model("conversations", "LLM")

    try:
        llm = LLM.objects.get(identifier="whisper-1")
        # Check if LLM is in use before deleting
        if not llm.conversations_using_model.exists() and not llm.messages.exists():
            llm.delete()
            print("\nReverse Migration: Deleted Whisper-1 model\n")
        else:
            print("\nReverse Migration: Whisper-1 model is in use, skipping deletion\n")
    except LLM.DoesNotExist:
        print("\nReverse Migration: Whisper-1 model does not exist\n")


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0044_add_is_audio_transcriber"),
    ]

    operations = [
        migrations.RunPython(seed_whisper_model, reverse_seed),
    ]
