# Generated by Django on 2025-12-18

from django.db import migrations


def seed_gpt4o_diarize_model(apps, schema_editor):
    """
    Seed GPT-4o Transcribe Diarize audio transcription model.
    Uses get_or_create to avoid duplicating if it already exists.
    """
    LLM = apps.get_model("conversations", "LLM")

    # GPT-4o Transcribe Diarize model data
    # Pricing: $0.006 per minute of audio (same as Whisper-1)
    model_data = {
        "name": "GPT-4o Transcribe Diarize",
        "identifier": "gpt-4o-transcribe-diarize",
        "provider": "openai",
        "description": "OpenAI's speech-to-text transcription model with speaker diarization. Automatically identifies and labels different speakers in audio. Supports 99+ languages.",
        "is_reasoning": False,
        "is_image_generator": False,
        "is_audio_transcriber": True,
        "supports_vision": False,
        # Pricing is per minute, stored as token rate for consistency
        # $0.006 per minute (same as Whisper-1)
        "input_token_rate_per_million": 6.0,
        "output_token_rate_per_million": 0.0,
    }

    llm, created = LLM.objects.get_or_create(
        identifier=model_data["identifier"],
        defaults={
            "name": model_data["name"],
            "provider": model_data["provider"],
            "description": model_data["description"],
            "is_reasoning": model_data["is_reasoning"],
            "is_image_generator": model_data["is_image_generator"],
            "is_audio_transcriber": model_data["is_audio_transcriber"],
            "supports_vision": model_data.get("supports_vision", False),
            "input_token_rate_per_million": model_data["input_token_rate_per_million"],
            "output_token_rate_per_million": model_data["output_token_rate_per_million"],
        },
    )

    if created:
        print(f"\nGPT-4o Diarize Seed Migration: Created {model_data['name']} model\n")
    else:
        print(f"\nGPT-4o Diarize Seed Migration: {model_data['name']} model already exists (skipped)\n")


def reverse_seed(apps, schema_editor):
    """
    Reverse migration - remove the GPT-4o Transcribe Diarize model.
    Only removes if it's not referenced by any conversations or messages.
    """
    LLM = apps.get_model("conversations", "LLM")

    try:
        llm = LLM.objects.get(identifier="gpt-4o-transcribe-diarize")
        # Check if LLM is in use before deleting
        if not llm.conversations_using_model.exists() and not llm.messages.exists():
            llm.delete()
            print("\nReverse Migration: Deleted GPT-4o Transcribe Diarize model\n")
        else:
            print("\nReverse Migration: GPT-4o Transcribe Diarize model is in use, skipping deletion\n")
    except LLM.DoesNotExist:
        print("\nReverse Migration: GPT-4o Transcribe Diarize model does not exist\n")


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0045_seed_whisper_model"),
    ]

    operations = [
        migrations.RunPython(seed_gpt4o_diarize_model, reverse_seed),
    ]
