# Generated by Django 5.1.12 on 2025-12-28 19:26

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0046_seed_gpt4o_diarize_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSearchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('url', models.URLField(help_text='The URL of the source.', max_length=2048)),
                ('title', models.CharField(blank=True, help_text='The title of the source page.', max_length=500)),
                ('cited_text', models.TextField(blank=True, help_text='The text that was cited from this source (Claude only).')),
                ('page_age', models.CharField(blank=True, help_text='When the page was last updated (Claude only).', max_length=100)),
                ('provider', models.CharField(blank=True, help_text='The LLM provider that returned this source (openai, claude, gemini).', max_length=20)),
                ('message', models.ForeignKey(help_text='The message this source was cited in.', on_delete=django.db.models.deletion.CASCADE, related_name='web_search_sources', to='conversations.message')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['message'], name='websearch_message_idx')],
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
