# Generated by Django 5.1.12 on 2025-12-29 16:43

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0047_add_web_search_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('emotion', models.CharField(help_text="User's emotional response (love, happy, neutral, confused, sad).", max_length=20)),
                ('category', models.CharField(blank=True, help_text='Feedback category (bug, idea, ui, performance, docs, other).', max_length=20, null=True)),
                ('message', models.TextField(blank=True, help_text='Detailed feedback message from the user.')),
                ('screenshot', models.TextField(blank=True, help_text='Base64 encoded screenshot (optional).', null=True)),
                ('page', models.CharField(help_text='Page URL where feedback was submitted.', max_length=500)),
                ('browser_info', models.TextField(blank=True, help_text="User's browser information.")),
                ('user', models.ForeignKey(help_text='User who submitted this feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
