# Generated by Django 5.1.14 on 2025-12-12 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0048_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelCardData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("name_variants", models.JSONField(blank=True, default=list)),
                ("provider_name", models.CharField(max_length=255)),
                ("public_feedback", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "llm",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to LLM if this model is configured for use",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_card_data",
                        to="conversations.llm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Card Data",
                "verbose_name_plural": "Model Card Data",
            },
        ),
    ]
