# Generated by Django 5.1.14 on 2025-12-18 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0049_modelcarddata"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicFeedbackSourceCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cluster_index",
                    models.PositiveIntegerField(
                        help_text="Citation number [1], [2], etc. used in refs arrays"
                    ),
                ),
                (
                    "canonical_title",
                    models.CharField(
                        help_text="Primary title for this source cluster",
                        max_length=500,
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        help_text="Primary URL (e.g., the original paper, not the HN thread)",
                        max_length=2000,
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True,
                        help_text="arXiv ID, DOI, or other unique identifier if available",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_clusters",
                        to="conversations.modelcarddata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Public Feedback Source Cluster",
                "verbose_name_plural": "Public Feedback Source Clusters",
                "ordering": ["cluster_index"],
                "unique_together": {("model_card", "cluster_index")},
            },
        ),
        migrations.CreateModel(
            name="PublicFeedbackSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=2000)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("canonical", "Canonical Source"),
                            ("hackernews", "Hacker News"),
                            ("reddit", "Reddit"),
                            ("twitter", "Twitter/X"),
                            ("blog", "Blog Post"),
                            ("news", "News Article"),
                            ("review", "Review/OpenReview"),
                            ("forum", "Forum Discussion"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type of source for potential filtering",
                        max_length=20,
                    ),
                ),
                (
                    "page_date",
                    models.CharField(
                        blank=True,
                        help_text="Date string as returned by search (not normalized)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "snippet",
                    models.TextField(
                        blank=True, help_text="Text snippet from search results"
                    ),
                ),
                (
                    "originating_query",
                    models.CharField(
                        blank=True,
                        help_text="The search query that found this source",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="conversations.publicfeedbacksourcecluster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Public Feedback Source",
                "verbose_name_plural": "Public Feedback Sources",
                "ordering": ["source_type", "title"],
            },
        ),
    ]
