# Generated by Django 5.1.12 on 2026-01-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0050_publicfeedbacksourcecluster_publicfeedbacksource'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicfeedbacksource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
