# Generated by Django 5.1.12 on 2026-01-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0051_publicfeedbacksource_updated_at"),
        ("mcp", "0004_add_extra_env_vars"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="selected_mcp_servers",
            field=models.ManyToManyField(
                blank=True,
                help_text="MCP servers enabled for this conversation (tools become available to the LLM).",
                related_name="conversations",
                to="mcp.mcpserver",
            ),
        ),
    ]
