# Generated by Django 5.1.12 on 2026-01-14 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0052_add_selected_mcp_servers"),
        ("mcp", "0004_add_extra_env_vars"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageToolCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "tool_call_id",
                    models.CharField(
                        help_text="Unique ID from LLM (e.g., 'call_abc123' or 'toolu_abc123').",
                        max_length=100,
                    ),
                ),
                (
                    "server_slug",
                    models.CharField(
                        help_text="MCP server slug (e.g., 'slack').", max_length=100
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(
                        help_text="Name of the tool (e.g., 'channels_list').",
                        max_length=200,
                    ),
                ),
                (
                    "arguments",
                    models.JSONField(
                        default=dict, help_text="Arguments passed to the tool."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("awaiting_confirmation", "Awaiting Confirmation"),
                            ("executing", "Executing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the tool call.",
                        max_length=30,
                    ),
                ),
                (
                    "requires_confirmation",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this tool requires user confirmation before execution.",
                    ),
                ),
                (
                    "result",
                    models.TextField(
                        blank=True,
                        help_text="Result text from tool execution.",
                        null=True,
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if execution failed.",
                        null=True,
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the tool was executed.", null=True
                    ),
                ),
                (
                    "mcp_execution",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to the MCP execution audit record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_tool_calls",
                        to="mcp.mcptoolexecution",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="The AI message that requested this tool call.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_tool_calls",
                        to="conversations.message",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["message", "status"], name="mtc_msg_status_idx"
                    ),
                    models.Index(fields=["tool_call_id"], name="mtc_call_id_idx"),
                ],
            },
        ),
    ]
