# Generated by Django 5.1.12 on 2026-01-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0053_add_message_tool_call"),
        ("dare_tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="selected_dare_tools",
            field=models.ManyToManyField(
                blank=True,
                help_text="DARE tools enabled for this conversation.",
                related_name="conversations",
                to="dare_tools.daretool",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="content_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Metadata for content rendering (e.g., chart config, diagram type).",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="content_type",
            field=models.CharField(
                default="text",
                help_text="Type of content for rendering (text, mermaid_diagram, chart, image, audio).",
                max_length=30,
            ),
        ),
    ]
