# Generated by Django 5.1.12 on 2026-01-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0054_add_dare_tools_and_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="content_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="MIME-like content type (e.g., 'application/vnd.dare.chart+json', 'text/mermaid').",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="filename",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Filename with extension (e.g., 'chart.json', 'diagram.mmd') - determines renderer.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="source_tool",
            field=models.CharField(
                blank=True,
                default="",
                help_text="DARE tool that created this artifact (e.g., 'create_chart', 'create_diagram').",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="artifact_type",
            field=models.CharField(
                choices=[
                    ("document", "Document"),
                    ("code", "Code"),
                    ("diagram", "Diagram"),
                    ("chart", "Chart"),
                ],
                default="document",
                help_text="Type of artifact (document, code, diagram).",
                max_length=20,
            ),
        ),
    ]
