# Generated by Django 5.1.12 on 2026-01-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0056_add_react_artifact_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="last_memory_extracted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of last memory extraction from this conversation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="artifact_type",
            field=models.CharField(
                choices=[
                    ("document", "Document"),
                    ("code", "Code"),
                    ("diagram", "Diagram"),
                    ("chart", "Chart"),
                    ("react", "React Component"),
                ],
                default="document",
                help_text="Type of artifact (document, code, diagram).",
                max_length=20,
            ),
        ),
    ]
