# Generated by Django 5.1.12 on 2026-01-28 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("conversations", "0057_alter_artifact_artifact_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="selected_agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected agent template for this conversation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations_using_agent",
                to="agents.agent",
            ),
        ),
    ]
