# Generated by Django 5.1.15 on 2026-02-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0057_add_last_memory_extracted_at'),
        ('conversations', '0058_add_selected_agent_to_conversation'),
    ]

    operations = [
    ]
