# Generated by Django 5.1.11 on 2026-02-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0059_merge_20260205_1119"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Whether this conversation is published and visible to other users.",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the conversation was published.",
                null=True,
            ),
        ),
    ]
