# Generated by Django 5.1.11 on 2026-02-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0060_conversation_sharing"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="file_owner_id",
            field=models.IntegerField(
                blank=True,
                help_text="Original file owner's user ID for forked conversations. Used for vector search namespace.",
                null=True,
            ),
        ),
    ]
