# Generated by Django 5.1.12 on 2026-03-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0062_llm_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="carbon_g",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Estimated carbon emissions in grams CO2 equivalent.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="energy_wh",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Estimated energy consumption in Watt-hours.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="water_ml",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Estimated water usage in milliliters.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
