# Generated by Django 5.1.15 on 2026-04-06 16:52

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0064_backfill_energy_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_favorite",
            field=models.BooleanField(
                default=False,
                help_text="Whether this conversation is marked as a favorite by its owner.",
            ),
        ),
        migrations.CreateModel(
            name="ConversationGroupSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "group_number",
                    models.PositiveIntegerField(
                        help_text="Sequential group index for completed conversations."
                    ),
                ),
                (
                    "conversation_ids",
                    models.JSONField(
                        default=list,
                        help_text="Conversation IDs included in this summary group.",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="LLM-generated summary for the conversation group."
                    ),
                ),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                (
                    "llm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="conversations.llm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_group_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation Group Summary",
                "verbose_name_plural": "Conversation Group Summaries",
                "ordering": ["user", "group_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "group_number"),
                        name="unique_conversation_summary_group",
                    )
                ],
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
