# Generated by Django 5.1.15 on 2026-04-07 00:00

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0065_conversation_is_favorite_conversationgroupsummary"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationSummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("summary", models.TextField(help_text="LLM-generated summary for the conversation.")),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("summarized_message_count", models.PositiveIntegerField(default=0, help_text="Number of completed AI assistant messages covered by this summary.")),
                ("conversation", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="conversation_summary", to="conversations.conversation")),
                ("llm", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="conversations.llm")),
            ],
            options={
                "verbose_name": "Conversation Summary",
                "verbose_name_plural": "Conversation Summaries",
                "ordering": ["-updated_at"],
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name="ConversationGroupSummary",
        ),
    ]
