# Generated by Django 5.1.15 on 2026-04-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0066_conversation_summary_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='memory_context_data',
            field=models.JSONField(blank=True, default=list, help_text='Memory items used as context for this message. List of {content, memory_type, categories}.'),
        ),
    ]
