# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0070_message_litellm_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="web_fetch_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable Claude web fetch for user-provided URLs and PDFs.",
            ),
        ),
    ]
