# Generated by Django 5.1.12 on 2026-05-25 22:31

from django.db import migrations, models


def backfill_tool_call_origin(apps, schema_editor):
    MessageToolCall = apps.get_model('conversations', 'MessageToolCall')
    MessageToolCall.objects.filter(server_slug='dare').update(origin='dare')
    MessageToolCall.objects.filter(server_slug='anthropic').update(origin='provider')


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0071_conversation_web_fetch_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetoolcall',
            name='origin',
            field=models.CharField(choices=[('dare', 'DARE'), ('mcp', 'MCP'), ('provider', 'Provider')], default='mcp', help_text='Execution origin: DARE internal, MCP external, or provider-native.', max_length=20),
        ),
        migrations.AlterField(
            model_name='messagetoolcall',
            name='server_slug',
            field=models.CharField(help_text="Concrete tool server/provider slug (e.g., 'slack', 'dare', 'anthropic').", max_length=100),
        ),
        migrations.RunPython(backfill_tool_call_origin, migrations.RunPython.noop),
    ]
