# Generated by Django 5.1.15 on 2026-04-07 12:10

import core.fields
import core.models
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DareConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "project_email",
                    models.EmailField(
                        help_text="Project-level email identity used for shared integrations.",
                        max_length=254,
                        unique=True,
                        verbose_name="Project Email",
                    ),
                ),
                (
                    "syftbox_access_token",
                    core.fields.EncryptedCharField(
                        blank=True,
                        help_text="Latest Syftbox OAuth access token for this project config",
                        null=True,
                        verbose_name="Syftbox Access Token",
                    ),
                ),
                (
                    "syftbox_refresh_token",
                    core.fields.EncryptedCharField(
                        blank=True,
                        help_text="Latest Syftbox OAuth refresh token for this project config",
                        null=True,
                        verbose_name="Syftbox Refresh Token",
                    ),
                ),
            ],
            options={
                "verbose_name": "DARE Config",
                "verbose_name_plural": "DARE Configs",
                "ordering": ["-updated_at"],
            },
            bases=(core.models.SyftBoxTokenMixin, models.Model),
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
