# Generated by Django 5.1.6 on 2025-03-30 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0006_message_llm"),
        ("files", "0004_file_job_id_file_status"),
        ("workflows", "0005_alter_step_options_alter_step_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="file",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional file associated with this step.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_steps",
                to="files.file",
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="llm",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional language model for this step.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_steps",
                to="conversations.llm",
            ),
        ),
    ]
