# Generated by Django 5.1.8 on 2025-05-12 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0006_step_file_step_llm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when the run ended.", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who initiated this run.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="Workflow being executed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkflowRunStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Order of this step in the run."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of this step.",
                        max_length=20,
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True, help_text="Response from step execution.", null=True
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True, help_text="Error message if step failed.", null=True
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        help_text="Step being executed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflows.step",
                    ),
                ),
                (
                    "workflow_run",
                    models.ForeignKey(
                        help_text="Workflow run this step belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="workflows.workflowrun",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
