# Generated by Django 5.1.8 on 2025-05-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0007_workflowrun_workflowrunstep"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="max_tokens",
            field=models.PositiveIntegerField(
                default=2048, help_text="Maximum tokens for LLM response for this step."
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="temperature",
            field=models.FloatField(
                default=0.7, help_text="Temperature setting for the LLM for this step."
            ),
        ),
    ]
