# Generated by Django 5.1.11 on 2025-06-14 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0007_folder"),
        ("workflows", "0009_step_document_similarity_threshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="embeddings",
            field=models.ManyToManyField(
                blank=True,
                help_text="Files to be processed using embeddings/vector search.",
                related_name="workflow_steps_embeddings",
                to="files.file",
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="files",
            field=models.ManyToManyField(
                blank=True,
                help_text="Files to be processed with full content.",
                related_name="workflow_steps_files",
                to="files.file",
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="file",
            field=models.ForeignKey(
                blank=True,
                help_text="Legacy single file field (deprecated).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_steps_legacy",
                to="files.file",
            ),
        ),
    ]
