# Generated by Django 5.1.11 on 2025-06-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0010_add_files_and_embeddings_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="step",
            name="file",
        ),
        migrations.RemoveField(
            model_name="step",
            name="is_embeddings",
        ),
    ]
