# Generated by Django 5.1.11 on 2025-07-18 06:09

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_file_error_message'),
        ('workflows', '0012_merge_20250619_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStepSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('text', models.TextField(help_text='The text content of the snippet (chunk).')),
                ('similarity_score', models.FloatField(help_text='The similarity score of the snippet to the query.')),
                ('chunk_index', models.PositiveIntegerField(help_text='The index of the chunk in the original file.')),
                ('vector_db_source', models.CharField(blank=True, help_text="The vector database source (e.g., 'pinecone', 'weaviate').", max_length=50, null=True)),
                ('file', models.ForeignKey(help_text='The file this snippet belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step_snippets', to='files.file')),
                ('workflow_run_step', models.ForeignKey(help_text='The workflow run step this snippet was retrieved for.', on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='workflows.workflowrunstep')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
