# Generated by Django 5.1.11 on 2025-08-03 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0014_add_previous_step_file_options"),
        ("workflows", "0014_step_use_previous_step_embeddings_and_more"),
    ]

    operations = []
