# Generated by Django 5.1.12 on 2025-09-30
# STEP 1: Create new node-based tables
# Old fields (layout, viewport) kept temporarily for data migration in 0019

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("conversations", "0025_conversation_source"),
        ("files", "0008_file_error_message"),
        ("prompts", "0003_prompt_parent"),
        ("workflows", "0017_add_viewport_to_workflow"),
    ]

    operations = [
        # Create node data models
        migrations.CreateModel(
            name="StartNodeData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Workflow title", max_length=255)),
                ("description", models.TextField(help_text="Workflow description")),
                ("mode", models.CharField(choices=[("sequential", "Sequential"), ("parallel", "Parallel")], default="sequential", help_text="Workflow execution mode", max_length=20)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="StepNodeData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step_number", models.PositiveIntegerField(help_text="Step order in workflow")),
                ("max_tokens", models.PositiveIntegerField(default=2000, help_text="Maximum tokens for LLM response")),
                ("temperature", models.FloatField(default=0.7, help_text="Temperature setting for the LLM", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ("max_context_snippets", models.PositiveIntegerField(default=5, help_text="Maximum number of context snippets to retrieve")),
                ("document_similarity_threshold", models.FloatField(default=0.7, help_text="Similarity threshold for document retrieval")),
                ("use_previous_step_files", models.BooleanField(default=False, help_text="Inherit files from previous step")),
                ("use_previous_step_embeddings", models.BooleanField(default=False, help_text="Inherit embeddings from previous step")),
                ("content_files", models.ManyToManyField(blank=True, help_text="Files to be processed with full content", related_name="step_node_content", to="files.file")),
                ("embedding_files", models.ManyToManyField(blank=True, help_text="Files to be processed using embeddings/vector search", related_name="step_node_embeddings", to="files.file")),
                ("llm", models.ForeignKey(blank=True, help_text="Language model for this step", null=True, on_delete=django.db.models.deletion.SET_NULL, to="conversations.llm")),
                ("prompt", models.ForeignKey(help_text="Prompt template for this step", on_delete=django.db.models.deletion.PROTECT, to="prompts.prompt")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ChatOutputNodeData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step_number", models.PositiveIntegerField(help_text="Associated step number for output")),
                ("status", models.CharField(blank=True, help_text="Execution status", max_length=20)),
                ("response", models.TextField(blank=True, help_text="Step execution response")),
                ("error", models.TextField(blank=True, help_text="Error message if step failed")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ConditionalNodeData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_prompt", models.TextField(default="Evaluate the input and choose the appropriate route.", help_text="Custom evaluation prompt for routing decision")),
                ("route_a_name", models.CharField(default="Route A", help_text="Name for route A output", max_length=100)),
                ("route_b_name", models.CharField(default="Route B", help_text="Name for route B output", max_length=100)),
                ("route_a_description", models.TextField(blank=True, help_text="Optional description for route A")),
                ("route_b_description", models.TextField(blank=True, help_text="Optional description for route B")),
                ("step_number", models.PositiveIntegerField(help_text="Step number for execution ordering")),
            ],
            options={"abstract": False},
        ),

        # Create WorkflowNode and WorkflowEdge models
        migrations.CreateModel(
            name="WorkflowNode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("node_id", models.CharField(help_text="Unique identifier for React Flow node (node.id)", max_length=255)),
                ("node_type", models.CharField(help_text="React Flow node type (node.type): step, start, chatOutput, conditional", max_length=100)),
                ("position_x", models.FloatField(help_text="X coordinate (node.position.x)")),
                ("position_y", models.FloatField(help_text="Y coordinate (node.position.y)")),
                ("width", models.FloatField(blank=True, help_text="Node width (calculated by React Flow, read-only)", null=True)),
                ("height", models.FloatField(blank=True, help_text="Node height (calculated by React Flow, read-only)", null=True)),
                ("selected", models.BooleanField(default=False, help_text="Selection state (node.selected)")),
                ("dragging", models.BooleanField(default=False, help_text="Current drag status (node.dragging)")),
                ("draggable", models.BooleanField(default=True, help_text="Can node be dragged (node.draggable)")),
                ("selectable", models.BooleanField(default=True, help_text="Can node be selected (node.selectable)")),
                ("connectable", models.BooleanField(default=True, help_text="Can node have connections (node.connectable)")),
                ("deletable", models.BooleanField(default=True, help_text="Can node be deleted (node.deletable)")),
                ("hidden", models.BooleanField(default=False, help_text="Node visibility (node.hidden)")),
                ("source_position", models.CharField(blank=True, help_text="Controls source connection point (node.sourcePosition): top/bottom/left/right", max_length=20, default="")),
                ("target_position", models.CharField(blank=True, help_text="Controls target connection point (node.targetPosition): top/bottom/left/right", max_length=20, default="")),
                ("parent_id", models.CharField(blank=True, help_text="Parent node for sub-flows (node.parentId)", max_length=255, null=True)),
                ("z_index", models.IntegerField(default=0, help_text="Rendering layer (node.zIndex)")),
                ("drag_handle", models.CharField(blank=True, help_text="CSS class for drag handles (node.dragHandle)", max_length=255, default="")),
                ("style", models.JSONField(blank=True, default=dict, help_text="CSS properties for node styling (node.style)")),
                ("class_name", models.CharField(blank=True, help_text="CSS class names (node.className)", max_length=500, default="")),
                ("data_object_id", models.PositiveIntegerField(help_text="ID of the associated node data object")),
                ("data_content_type", models.ForeignKey(help_text="Content type of the associated node data", on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype")),
                ("workflow", models.ForeignKey(help_text="Workflow this node belongs to", on_delete=django.db.models.deletion.CASCADE, related_name="nodes", to="workflows.workflow")),
            ],
            options={"ordering": ["node_id"]},
        ),
        migrations.CreateModel(
            name="WorkflowEdge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("edge_id", models.CharField(help_text="Unique identifier for React Flow edge (edge.id)", max_length=255)),
                ("edge_type", models.CharField(default="default", help_text="Edge type: default/straight/step/smoothstep/simplebezier (edge.type)", max_length=100)),
                ("source", models.CharField(help_text="Source node ID (edge.source)", max_length=255)),
                ("target", models.CharField(help_text="Target node ID (edge.target)", max_length=255)),
                ("source_handle", models.CharField(blank=True, help_text="Source handle ID (edge.sourceHandle)", max_length=255, null=True)),
                ("target_handle", models.CharField(blank=True, help_text="Target handle ID (edge.targetHandle)", max_length=255, null=True)),
                ("data", models.JSONField(default=dict, help_text="Arbitrary edge data (edge.data)")),
                ("selected", models.BooleanField(default=False, help_text="Selection state (edge.selected)")),
                ("animated", models.BooleanField(default=False, help_text="Animation state (edge.animated)")),
                ("hidden", models.BooleanField(default=False, help_text="Edge visibility (edge.hidden)")),
                ("deletable", models.BooleanField(default=True, help_text="Can edge be deleted (edge.deletable)")),
                ("selectable", models.BooleanField(default=True, help_text="Can edge be selected (edge.selectable)")),
                ("z_index", models.IntegerField(default=0, help_text="Rendering layer (edge.zIndex)")),
                ("label", models.TextField(blank=True, help_text="Edge label text (edge.label)")),
                ("style", models.JSONField(blank=True, default=dict, help_text="CSS properties for edge styling (edge.style)")),
                ("class_name", models.CharField(blank=True, help_text="CSS class names (edge.className)", max_length=500, default="")),
                ("marker_start", models.JSONField(blank=True, default=dict, help_text="Start marker configuration (edge.markerStart)")),
                ("marker_end", models.JSONField(blank=True, default=dict, help_text="End marker configuration (edge.markerEnd)")),
                ("path_options", models.JSONField(blank=True, default=dict, help_text="Path configuration for smoothstep/bezier edges (edge.pathOptions)")),
                ("workflow", models.ForeignKey(help_text="Workflow this edge belongs to", on_delete=django.db.models.deletion.CASCADE, related_name="edges", to="workflows.workflow")),
            ],
            options={"ordering": ["edge_id"]},
        ),

        # Add unique constraints
        migrations.AddConstraint(
            model_name="workflownode",
            constraint=models.UniqueConstraint(fields=("workflow", "node_id"), name="unique_workflow_node"),
        ),
        migrations.AddConstraint(
            model_name="workflowedge",
            constraint=models.UniqueConstraint(fields=("workflow", "edge_id"), name="unique_workflow_edge"),
        ),

        # NOTE: layout and viewport fields kept temporarily for 0019 data migration
        # They will be removed in 0020
    ]