# Generated by Django 5.1.12 on 2025-09-30
# STEP 2: Migrate existing workflow data to new node-based structure
# This runs automatically during `python manage.py migrate`

from django.db import migrations


def migrate_workflows_to_nodes(apps, schema_editor):
    """
    Migrate existing workflows from old Step-based structure to new node-based structure.
    This function runs automatically during migration - no manual command needed!
    """
    # Get models through the apps registry (proper way in migrations)
    Workflow = apps.get_model('workflows', 'Workflow')
    Step = apps.get_model('workflows', 'Step')
    WorkflowNode = apps.get_model('workflows', 'WorkflowNode')
    WorkflowEdge = apps.get_model('workflows', 'WorkflowEdge')
    StartNodeData = apps.get_model('workflows', 'StartNodeData')
    StepNodeData = apps.get_model('workflows', 'StepNodeData')
    ChatOutputNodeData = apps.get_model('workflows', 'ChatOutputNodeData')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Get the through table for workflow-step many-to-many relationship
    WorkflowSteps = apps.get_model('workflows', 'Workflow_steps')

    # Get content types for generic foreign keys
    start_ct = ContentType._default_manager.get_for_model(StartNodeData, for_concrete_model=False)
    step_ct = ContentType._default_manager.get_for_model(StepNodeData, for_concrete_model=False)
    output_ct = ContentType._default_manager.get_for_model(ChatOutputNodeData, for_concrete_model=False)

    workflows_migrated = 0

    # Check if old fields exist in Workflow table
    # They should exist in normal migrations, but may not exist if rollback was done
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("PRAGMA table_info(workflows_workflow);")
        workflow_columns = {row[1] for row in cursor.fetchall()}

    has_legacy_fields = {'title', 'description', 'mode'}.issubset(workflow_columns)

    # Get all workflow IDs using raw SQL to avoid ORM model field issues
    with schema_editor.connection.cursor() as cursor:
        if has_legacy_fields:
            cursor.execute("SELECT id, title, description, mode FROM workflows_workflow")
            workflow_rows = cursor.fetchall()
        else:
            cursor.execute("SELECT id FROM workflows_workflow")
            workflow_rows = [(row[0], None, None, None) for row in cursor.fetchall()]

    # Process each workflow
    for workflow_row in workflow_rows:
        workflow_id = workflow_row[0]

        # Skip if already has nodes (avoid duplicate migration)
        if WorkflowNode._default_manager.filter(workflow_id=workflow_id).exists():
            continue

        # Create a minimal workflow instance just for FK references
        # We use _state to create an instance without loading from DB
        workflow = Workflow(id=workflow_id)
        workflow._state.adding = False  # Mark as existing record, not new

        # Migrate title/description/mode from Workflow to StartNodeData if they exist
        if has_legacy_fields:
            title = workflow_row[1] or 'Untitled Workflow'
            description = workflow_row[2] or ''
            mode_int = workflow_row[3]

            # Convert mode integer to string
            mode_map = {1: 'sequential', 2: 'parallel'}
            mode_str = mode_map.get(mode_int, 'sequential')

            start_data = StartNodeData._default_manager.create(
                title=title,
                description=description,
                mode=mode_str
            )
        else:
            # Legacy fields don't exist (e.g., after rollback), use defaults
            start_data = StartNodeData._default_manager.create(
                title='Untitled Workflow',
                description='',
                mode='sequential'
            )

        # Create start node
        start_node = WorkflowNode._default_manager.create(
            workflow=workflow,
            node_id='start-node',
            node_type='start',
            position_x=100.0,
            position_y=100.0,
            data_content_type=start_ct,
            data_object_id=start_data.id
        )

        # Get steps for this workflow through the many-to-many table
        workflow_step_relations = WorkflowSteps._default_manager.filter(workflow=workflow).order_by('id')
        steps = [Step._default_manager.get(id=ws.step_id) for ws in workflow_step_relations]

        previous_node_id = 'start-node'
        x_offset = 300.0

        for idx, step in enumerate(steps, start=1):
            # Create StepNodeData
            step_data = StepNodeData._default_manager.create(
                prompt_id=step.prompt_id,
                step_number=idx,
                max_tokens=step.max_tokens or 2000,
                temperature=step.temperature or 0.7,
                document_similarity_threshold=step.document_similarity_threshold or 0.7,
                max_context_snippets=step.max_context_snippets or 5,
                use_previous_step_files=step.use_previous_step_files or False,
                use_previous_step_embeddings=step.use_previous_step_embeddings or False,
                llm_id=step.llm_id
            )

            # Copy M2M relationships for files and embeddings
            step_data.content_files.set(step.files.all())
            step_data.embedding_files.set(step.embeddings.all())

            # Create WorkflowNode for step
            step_node_id = f'step-{idx}'
            step_node = WorkflowNode._default_manager.create(
                workflow=workflow,
                node_id=step_node_id,
                node_type='step',
                position_x=x_offset,
                position_y=100.0,
                data_content_type=step_ct,
                data_object_id=step_data.id
            )

            # Create edge from previous node to this step
            WorkflowEdge._default_manager.create(
                workflow=workflow,
                edge_id=f'e-{previous_node_id}-{step_node_id}',
                source=previous_node_id,
                target=step_node_id,
                edge_type='default'
            )

            # Create ChatOutputNodeData for this step
            output_data = ChatOutputNodeData._default_manager.create(
                step_number=idx,
                status='',
                response='',
                error=''
            )

            # Create WorkflowNode for output
            output_node_id = f'output-{idx}'
            output_node = WorkflowNode._default_manager.create(
                workflow=workflow,
                node_id=output_node_id,
                node_type='chatOutput',
                position_x=x_offset,
                position_y=300.0,
                data_content_type=output_ct,
                data_object_id=output_data.id
            )

            # Create edge from step to output
            WorkflowEdge._default_manager.create(
                workflow=workflow,
                edge_id=f'e-{step_node_id}-{output_node_id}',
                source=step_node_id,
                target=output_node_id,
                edge_type='default'
            )

            # Update for next iteration
            previous_node_id = output_node_id
            x_offset += 250.0

        workflows_migrated += 1

    if workflows_migrated > 0:
        print(f"\n✅ Successfully migrated {workflows_migrated} workflow(s) to node-based structure")
    else:
        print("\n✅ No workflows needed migration (already migrated or none exist)")


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by deleting all created nodes and edges.
    """
    WorkflowNode = apps.get_model('workflows', 'WorkflowNode')
    WorkflowEdge = apps.get_model('workflows', 'WorkflowEdge')
    StartNodeData = apps.get_model('workflows', 'StartNodeData')
    StepNodeData = apps.get_model('workflows', 'StepNodeData')
    ChatOutputNodeData = apps.get_model('workflows', 'ChatOutputNodeData')
    ConditionalNodeData = apps.get_model('workflows', 'ConditionalNodeData')

    # Delete all created data
    WorkflowEdge._default_manager.all().delete()
    WorkflowNode._default_manager.all().delete()
    StartNodeData._default_manager.all().delete()
    StepNodeData._default_manager.all().delete()
    ChatOutputNodeData._default_manager.all().delete()
    ConditionalNodeData._default_manager.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0018_create_node_tables'),
    ]

    operations = [
        migrations.RunPython(migrate_workflows_to_nodes, reverse_migration),
    ]