# Generated by Django 5.1.12 on 2025-09-30
# STEP 3: Remove old workflow fields after data migration is complete

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0019_migrate_data_to_nodes'),
    ]

    operations = [
        # Remove old fields that have been migrated to node-based structure
        # - layout, viewport: replaced by viewport_x/y/zoom (added in 0017)
        migrations.RemoveField(
            model_name="workflow",
            name="layout",
        ),
        migrations.RemoveField(
            model_name="workflow",
            name="viewport",
        ),
    ]