# Generated by Django 5.1.12 on 2025-09-30
# STEP 4: Add step_node field to WorkflowRunStep for new node-based execution

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0020_remove_old_workflow_fields'),
    ]

    operations = [
        # Add the new step_node field (nullable for backward compatibility with old run data)
        migrations.AddField(
            model_name='workflowrunstep',
            name='step_node',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='workflows.workflownode',
                limit_choices_to={'node_type': 'step'},
                help_text="Step node being executed (new node-based workflows)."
            ),
        ),
    ]