# Generated by Django 5.1.12 on 2025-09-30
# Make step_id nullable - new workflows use step_node, old workflows continue using step_id
# This keeps old data intact while allowing new node-based workflows to work

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0021_add_step_node_to_workflowrunstep'),
    ]

    operations = [
        # Make step_id nullable so new workflows (using step_node) don't need it
        # Old workflow run steps will still have step_id populated
        migrations.AlterField(
            model_name='workflowrunstep',
            name='step_id',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                to='workflows.step',
                help_text="Legacy: Step being executed in old workflows. New workflows use step_node instead."
            ),
        ),
    ]