# Generated by Django 5.1.12 on 2025-10-10 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0028_migrate_legacy_routes_to_new_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='workflow',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='workflowrunstep',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata about step execution (e.g., AI analysis, routing decisions)', null=True),
        ),
        migrations.AlterField(
            model_name='chatoutputnodedata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='conditionalnodedata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='startnodedata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stepnodedata',
            name='document_similarity_threshold',
            field=models.FloatField(default=0.2, help_text='Similarity threshold for document retrieval'),
        ),
        migrations.AlterField(
            model_name='stepnodedata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stepnodedata',
            name='max_context_snippets',
            field=models.PositiveIntegerField(default=4, help_text='Maximum number of context snippets to retrieve'),
        ),
        migrations.AlterField(
            model_name='stepnodedata',
            name='max_tokens',
            field=models.PositiveIntegerField(default=2048, help_text='Maximum tokens for LLM response'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Original workflow this was cloned from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='workflows.workflow'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='user',
            field=models.ForeignKey(help_text='User who owns this workflow', on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflowedge',
            name='class_name',
            field=models.CharField(blank=True, help_text='CSS class names (edge.className)', max_length=500),
        ),
        migrations.AlterField(
            model_name='workflowedge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='class_name',
            field=models.CharField(blank=True, help_text='CSS class names (node.className)', max_length=500),
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='drag_handle',
            field=models.CharField(blank=True, help_text='CSS class for drag handles (node.dragHandle)', max_length=255),
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='source_position',
            field=models.CharField(blank=True, help_text='Controls source connection point (node.sourcePosition): top/bottom/left/right', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='target_position',
            field=models.CharField(blank=True, help_text='Controls target connection point (node.targetPosition): top/bottom/left/right', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowrunstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('pending_human_input', 'Pending Human Input')], default='pending', help_text='Current status of this step.', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowrunstep',
            name='step_node',
            field=models.ForeignKey(help_text='Step node being executed.', limit_choices_to={'node_type': 'step'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.workflownode'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowedge',
            unique_together={('workflow', 'edge_id')},
        ),
        migrations.AlterUniqueTogether(
            name='workflownode',
            unique_together={('workflow', 'node_id')},
        ),
    ]
