# Generated by Django 5.1.12 on 2025-10-10 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0026_llm_supports_vision"),
        ("workflows", "0029_add_metadata_to_workflow_run_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditionalnodedata",
            name="llm",
            field=models.ForeignKey(
                blank=True,
                help_text="Language model for routing evaluation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="conversations.llm",
            ),
        ),
    ]
