# Generated by Django 5.1.12 on 2025-10-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0030_add_llm_to_conditional_node"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conditionalnodedata",
            name="route_a_description",
        ),
        migrations.RemoveField(
            model_name="conditionalnodedata",
            name="route_a_name",
        ),
        migrations.RemoveField(
            model_name="conditionalnodedata",
            name="route_b_description",
        ),
        migrations.RemoveField(
            model_name="conditionalnodedata",
            name="route_b_name",
        ),
    ]
