# Generated by Django 5.1.12 on 2025-10-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0031_remove_conditionalnodedata_route_a_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StructuredOutputNodeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "routes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of route definitions: [{'name': '1', 'description': '...'}, ...]",
                    ),
                ),
                (
                    "step_number",
                    models.PositiveIntegerField(
                        help_text="Step number for execution ordering"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="stepnodedata",
            name="text_input",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional text input to be passed directly to the LLM",
            ),
        ),
    ]
