# Generated by Django 5.1.12 on 2025-10-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0032_add_text_input_and_structured_output_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="stepnodedata",
            name="use_structured_output_node",
            field=models.BooleanField(
                default=False,
                help_text="If true, this step uses a separate StructuredOutputNode for routing",
            ),
        ),
    ]
