# Generated by Django 5.1.12 on 2025-11-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0033_add_use_structured_output_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="structuredoutputnodedata",
            name="require_human_validation",
            field=models.BooleanField(
                default=False,
                help_text="If true, pause execution and ask user to choose route",
            ),
        ),
    ]
