# Generated by Django 5.1.12 on 2025-11-02 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0034_make_user_nullable_add_session_id"),
        ("workflows", "0034_add_require_human_validation_to_structured_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="structuredoutputnodedata",
            name="llm",
            field=models.ForeignKey(
                blank=True,
                help_text="Language model for routing evaluation (used when human validation is enabled)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="conversations.llm",
            ),
        ),
    ]
