# Generated by Django 5.1.12 on 2025-11-02 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0034_make_user_nullable_add_session_id"),
        ("prompts", "0003_prompt_parent"),
        ("workflows", "0035_add_llm_to_structured_output"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conditionalnodedata",
            name="custom_prompt",
        ),
        migrations.AddField(
            model_name="conditionalnodedata",
            name="prompt",
            field=models.ForeignKey(
                blank=True,
                help_text="Prompt template for routing evaluation",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="prompts.prompt",
            ),
        ),
        migrations.AddField(
            model_name="structuredoutputnodedata",
            name="prompt",
            field=models.ForeignKey(
                blank=True,
                help_text="Prompt template for routing evaluation",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="prompts.prompt",
            ),
        ),
        migrations.AlterField(
            model_name="structuredoutputnodedata",
            name="llm",
            field=models.ForeignKey(
                blank=True,
                help_text="Language model for routing evaluation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="conversations.llm",
            ),
        ),
    ]
