# Generated by Django 5.1.12 on 2025-11-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0036_unify_node_prompts'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['workflow', 'node_type'], name='wf_node_type_idx'),
        ),
    ]
