# Generated by Django 5.1.12 on 2025-11-02 14:22

from django.db import migrations


def drop_require_human_validation_structured(apps, schema_editor):
    """Drop the orphaned require_human_validation_structured column from stepnodedata table."""
    if schema_editor.connection.vendor == 'sqlite':
        # SQLite requires recreating the table without the column
        schema_editor.execute("""
            CREATE TABLE "workflows_stepnodedata_new" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "created_at" datetime NOT NULL,
                "updated_at" datetime NOT NULL,
                "step_number" integer unsigned NOT NULL CHECK ("step_number" >= 0),
                "max_tokens" integer unsigned NOT NULL CHECK ("max_tokens" >= 0),
                "temperature" real NOT NULL,
                "max_context_snippets" integer unsigned NOT NULL CHECK ("max_context_snippets" >= 0),
                "document_similarity_threshold" real NOT NULL,
                "use_previous_step_files" bool NOT NULL,
                "use_previous_step_embeddings" bool NOT NULL,
                "llm_id" bigint NULL REFERENCES "conversations_llm" ("id") DEFERRABLE INITIALLY DEFERRED,
                "prompt_id" bigint NOT NULL REFERENCES "prompts_prompt" ("id") DEFERRABLE INITIALLY DEFERRED,
                "text_input" text NOT NULL,
                "use_structured_output_node" bool NOT NULL
            );
        """)
        schema_editor.execute("""
            INSERT INTO "workflows_stepnodedata_new"
            SELECT id, created_at, updated_at, step_number, max_tokens, temperature,
                   max_context_snippets, document_similarity_threshold, use_previous_step_files,
                   use_previous_step_embeddings, llm_id, prompt_id, text_input, use_structured_output_node
            FROM "workflows_stepnodedata";
        """)
        schema_editor.execute('DROP TABLE "workflows_stepnodedata";')
        schema_editor.execute('ALTER TABLE "workflows_stepnodedata_new" RENAME TO "workflows_stepnodedata";')
        schema_editor.execute('CREATE INDEX "workflows_stepnodedata_llm_id_7027755b" ON "workflows_stepnodedata" ("llm_id");')
        schema_editor.execute('CREATE INDEX "workflows_stepnodedata_prompt_id_8c6005f4" ON "workflows_stepnodedata" ("prompt_id");')
    else:
        schema_editor.execute('ALTER TABLE workflows_stepnodedata DROP COLUMN require_human_validation_structured;')


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0036_unify_node_prompts"),
    ]

    operations = [
        migrations.RunPython(drop_require_human_validation_structured, migrations.RunPython.noop),
    ]
