# Generated by Django 5.1.12 on 2025-11-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0037_add_composite_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workflownode',
            name='wf_node_type_idx',
        ),
        migrations.AddField(
            model_name='stepnodedata',
            name='enable_web_search',
            field=models.BooleanField(default=False, help_text="If true, enable web search for this step's LLM"),
        ),
    ]
