# Generated by Django 5.1.12 on 2025-11-13 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('workflows', '0038_remove_workflownode_wf_node_type_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepnodedata',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent template that was loaded for this step', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent'),
        ),
    ]
