# Generated by Django 5.1.12 on 2025-11-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0039_stepnodedata_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='is_partial',
            field=models.BooleanField(default=False, help_text='Whether this is a partial run (manual step-by-step execution) or complete workflow run.'),
        ),
    ]
