# Generated by Django 5.1.12 on 2025-11-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0040_workflowrun_is_partial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='manual_mode_enabled',
            field=models.BooleanField(default=False, help_text='Whether manual mode (step-by-step execution) is enabled for this workflow'),
        ),
    ]
