# Generated by Django 5.1.12 on 2025-11-24 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0003_prompt_parent"),
        ("workflows", "0042_refactor_structured_output_independence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structuredoutputnodedata",
            name="prompt",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional prompt template for routing evaluation (falls back to base prompt if not provided)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="prompts.prompt",
            ),
        ),
    ]
