# Generated by Django 5.1.12 on 2025-11-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0043_alter_structuredoutputnodedata_prompt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workflow",
            options={"ordering": ["display_order", "-created_at"]},
        ),
        migrations.AddField(
            model_name="workflow",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Order in which workflows are displayed in the UI. Higher values appear later.",
            ),
        ),
    ]
