# Generated by Django 5.1.12 on 2025-11-27 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0003_prompt_parent"),
        ("workflows", "0044_alter_workflow_options_workflow_display_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stepnodedata",
            name="prompt",
            field=models.ForeignKey(
                blank=True,
                help_text="Prompt template for this step (required for execution)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="prompts.prompt",
            ),
        ),
    ]
