# Generated by Django 5.1.12 on 2025-11-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0045_alter_stepnodedata_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startnodedata",
            name="description",
            field=models.TextField(
                blank=True, help_text="Workflow description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="startnodedata",
            name="title",
            field=models.CharField(
                blank=True, help_text="Workflow title", max_length=255, null=True
            ),
        ),
    ]
