# Generated by Django 5.1.12 on 2025-12-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0048_remove_conditionalnodedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(help_text='React Flow node type (node.type): step, start, chatOutput, structuredOutput', max_length=100),
        ),
    ]
