# Generated by Django 5.1.12 on 2025-12-29 15:27

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to add workflow step citation models.

    Note: WorkflowStepSnippet table already exists in the database from migration 0013
    (which was later removed from Django's state in 0027). We use SeparateDatabaseAndState
    to re-register it in Django's migration state without attempting to create the table.
    """

    dependencies = [
        ('files', '0012_add_audio_media_type'),
        ('workflows', '0049_alter_workflownode_node_type'),
    ]

    operations = [
        # Register WorkflowStepSnippet in Django's migration state without creating table
        # The table already exists from migration 0013 (before it was removed from state in 0027)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='WorkflowStepSnippet',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('is_active', models.BooleanField(default=True)),
                        ('is_deleted', models.BooleanField(default=False)),
                        ('text', models.TextField(help_text='The text content of the snippet (chunk).')),
                        ('similarity_score', models.FloatField(help_text='The similarity score of the snippet to the query.')),
                        ('chunk_index', models.PositiveIntegerField(help_text='The index of the chunk in the original file.')),
                        ('vector_db_source', models.CharField(blank=True, help_text="The vector database source (e.g., 'pinecone', 'weaviate').", max_length=50, null=True)),
                        ('file', models.ForeignKey(help_text='The file this snippet belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step_snippets', to='files.file')),
                        ('workflow_run_step', models.ForeignKey(help_text='The workflow run step this snippet was retrieved for.', on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='workflows.workflowrunstep')),
                    ],
                    options={
                        'abstract': False,
                    },
                    managers=[
                        ('active_objects', django.db.models.manager.Manager()),
                    ],
                ),
            ],
            database_operations=[],  # Table already exists, don't create it
        ),
        # Create the new WebSearchSource table (this one is actually new)
        migrations.CreateModel(
            name='WorkflowStepWebSearchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('url', models.URLField(help_text='The URL of the source.', max_length=2048)),
                ('title', models.CharField(blank=True, help_text='The title of the source page.', max_length=500)),
                ('cited_text', models.TextField(blank=True, help_text='The text that was cited from this source (Claude only).')),
                ('page_age', models.CharField(blank=True, help_text='When the page was last updated (Claude only).', max_length=100)),
                ('provider', models.CharField(blank=True, help_text='The LLM provider that returned this source (openai, claude, gemini).', max_length=20)),
                ('workflow_run_step', models.ForeignKey(help_text='The workflow run step this source was cited in.', on_delete=django.db.models.deletion.CASCADE, related_name='web_search_sources', to='workflows.workflowrunstep')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['workflow_run_step'], name='wf_websearch_step_idx')],
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
