# Generated by Django 5.1.12 on 2026-02-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0050_add_workflow_step_citations'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='output_display_mode',
            field=models.CharField(choices=[('panel', 'Panel'), ('nodes', 'Nodes')], default='panel', help_text="Where to display workflow output: 'panel' (execution panel) or 'nodes' (output nodes)", max_length=10),
        ),
    ]
