# Generated by Django 5.1.12 on 2026-02-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0051_add_output_display_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotesNodeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Note content/documentation text",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
