# Generated by Django 5.1.15 on 2026-02-05 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_add_audio_media_type'),
        ('workflows', '0052_notesnodedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileNodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retrieval_mode', models.CharField(choices=[('embeddings', 'Embeddings (Vector Search)'), ('content', 'Full Content'), ('both', 'Both Embeddings and Content')], default='embeddings', help_text='How to retrieve file content', max_length=20)),
                ('similarity_threshold', models.FloatField(default=0.5, help_text='Minimum similarity score for vector search results (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('max_results', models.PositiveIntegerField(default=10, help_text='Maximum number of snippets to retrieve')),
                ('query_source', models.CharField(choices=[('previous_step', 'Previous Step Output'), ('text_input', 'Text Input')], default='previous_step', help_text='Source of query text for vector search', max_length=20)),
                ('text_input', models.TextField(blank=True, default='', help_text="Custom query text (used when query_source is 'text_input')")),
                ('include_metadata', models.BooleanField(default=True, help_text='Include file names and similarity scores in output')),
                ('step_number', models.PositiveIntegerField(help_text='Step order in workflow')),
                ('files', models.ManyToManyField(blank=True, help_text='Files to retrieve content from', related_name='file_node_files', to='files.file')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
