# Generated by Django 5.1.11 on 2026-02-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0053_filenodedata"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="file_owner_id",
            field=models.IntegerField(
                blank=True,
                help_text="Original owner's user ID for shared file/embedding access in forked workflows",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Whether this workflow is published and visible in the shared library",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the workflow was published",
                null=True,
            ),
        ),
    ]
