# Generated by Django 5.1.11 on 2026-02-12 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0005_change_prompt_on_delete_to_set_null"),
        ("workflows", "0054_workflow_publishing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stepnodedata",
            name="prompt",
            field=models.ForeignKey(
                blank=True,
                help_text="Prompt template for this step (required for execution)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prompts.prompt",
            ),
        ),
        migrations.AlterField(
            model_name="structuredoutputnodedata",
            name="prompt",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional prompt template for routing evaluation (falls back to base prompt if not provided)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prompts.prompt",
            ),
        ),
    ]
