# Generated by Django 5.1.15 on 2026-02-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0055_change_prompt_on_delete_to_set_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='file_owner_id',
        ),
    ]
