# Generated by Django 5.1.15 on 2026-02-19 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_add_audio_media_type'),
        ('workflows', '0056_remove_file_owner_id_from_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRun',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('running', 'Running'),
                            ('completed', 'Completed'),
                            ('failed', 'Failed'),
                        ],
                        default='running',
                        help_text='Batch execution status.',
                        max_length=20,
                    ),
                ),
                (
                    'total_files',
                    models.PositiveIntegerField(
                        default=0,
                        help_text='Total number of files in this batch.',
                    ),
                ),
                (
                    'completed_count',
                    models.PositiveIntegerField(
                        default=0,
                        help_text='Number of completed workflow runs in this batch.',
                    ),
                ),
                (
                    'failed_count',
                    models.PositiveIntegerField(
                        default=0,
                        help_text='Number of failed workflow runs in this batch.',
                    ),
                ),
                (
                    'ended_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='Timestamp when the batch finished.',
                        null=True,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text='User who initiated this batch run.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='workflow_batch_runs',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'workflow',
                    models.ForeignKey(
                        help_text='Workflow being executed in batch.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='batch_runs',
                        to='workflows.workflow',
                    ),
                ),
            ],
            managers=[
                ('active_objects', models.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='batch_file',
            field=models.ForeignKey(
                blank=True,
                help_text='File injected into start-connected steps for this batch run.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='batch_workflow_runs',
                to='files.file',
            ),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='batch_run',
            field=models.ForeignKey(
                blank=True,
                help_text='Batch run this workflow execution belongs to.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='workflow_runs',
                to='workflows.batchrun',
            ),
        ),
    ]
