# Generated by Django 5.1.15 on 2026-02-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0057_add_batch_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrunstep',
            name='started_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Timestamp when this step started executing.',
                null=True,
            ),
        ),
    ]
