# Generated by Django 5.1.15 on 2026-02-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0058_add_workflowrunstep_started_at"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="batchrun",
            managers=[],
        ),
    ]
