# Generated by Django 5.1.15 on 2026-03-26 20:28

import django.db.models.deletion
from django.db import migrations, models


def backfill_root_start_node(apps, schema_editor):
    """Resolve and store root_start_node for every existing workflow."""
    Workflow = apps.get_model("workflows", "Workflow")
    WorkflowNode = apps.get_model("workflows", "WorkflowNode")
    WorkflowEdge = apps.get_model("workflows", "WorkflowEdge")

    for workflow in Workflow.objects.all().iterator():
        start_nodes = list(
            WorkflowNode.objects.filter(workflow=workflow, node_type="start")
        )
        if not start_nodes:
            continue

        if len(start_nodes) == 1:
            root = start_nodes[0]
        else:
            edge_targets = set(
                WorkflowEdge.objects.filter(workflow=workflow).values_list(
                    "target", flat=True
                )
            )
            root = next(
                (sn for sn in start_nodes if sn.node_id not in edge_targets),
                None,
            )

        if root:
            Workflow.objects.filter(id=workflow.id).update(root_start_node=root)


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0061_step_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='root_start_node',
            field=models.ForeignKey(blank=True, help_text='Root start node (no incoming edges). Holds workflow title/description/mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflows.workflownode'),
        ),
        migrations.RunPython(backfill_root_start_node, migrations.RunPython.noop),
    ]
