# Generated by Django 5.1.15 on 2026-04-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0065_add_tags_to_stepnodedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepnodedata',
            name='use_previous_context',
            field=models.BooleanField(
                default=True,
                help_text="Include upstream step outputs in this step's prompt as a structured <workflow_context> block.",
            ),
        ),
    ]
