# Generated by Django 5.1.12 on 2026-05-08 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0032_multi_wallet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable identifier referenced by the frontend (snake_case).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="What this flag controls. Surfaced in the admin UI.",
                    ),
                ),
                (
                    "default_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="App-wide value used when no group/user override applies.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag",
                "verbose_name_plural": "Feature Flags",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="GroupFeatureOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField()),
                (
                    "flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_overrides",
                        to="feature_flags.featureflag",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_flag_overrides",
                        to="users.accesscodegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Feature Override",
                "verbose_name_plural": "Group Feature Overrides",
                "indexes": [
                    models.Index(
                        fields=["group", "flag"], name="feature_fla_group_i_8d3b40_idx"
                    )
                ],
                "unique_together": {("flag", "group")},
            },
        ),
        migrations.CreateModel(
            name="UserFeatureOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField()),
                (
                    "flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_overrides",
                        to="feature_flags.featureflag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_flag_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Feature Override",
                "verbose_name_plural": "User Feature Overrides",
                "indexes": [
                    models.Index(
                        fields=["user", "flag"], name="feature_fla_user_id_7e1001_idx"
                    )
                ],
                "unique_together": {("flag", "user")},
            },
        ),
    ]
