import random
import string

from django.db import models
from django.conf import settings

from common.managers import ActiveObjectsManager
from common.models import BaseModel, TimeStampMixin
from .constants import Provider, SenderType


class LLM(models.Model):
    name = models.CharField(max_length=255, help_text="Display name of the Language Model.")
    identifier = models.CharField(max_length=255, unique=True, help_text="Technical identifier used in API calls (e.g., claude-3.5-sonnet-20240307).")
    description = models.TextField(blank=True, null=True, help_text="Description of the language model capabilities.")
    provider = models.CharField(
        max_length=20,
        choices=Provider.choices(),
        default="openai",
        help_text="Provider of the LLM (e.g., OpenAI, Claude)."
    )
    is_reasoning = models.BooleanField(default=False, help_text="Whether the model supports reasoning.")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "LLMs"


class Conversation(BaseModel):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="conversations",
        help_text="User who owns this conversation."
    )
    conversation_id = models.CharField(max_length=10, unique=True, help_text="Unique conversation ID.")
    title = models.CharField(max_length=255, blank=True, null=True, help_text="Title of the conversation.")
    max_context_snippets = models.PositiveIntegerField(default=4, help_text="Maximum number of context snippets to retrieve.")
    document_similarity_threshold = models.FloatField(default=0.2, help_text="Similarity threshold for document retrieval.")
    temperature = models.FloatField(default=0.7, help_text="Temperature setting for the LLM.")
    max_tokens = models.PositiveIntegerField(default=2048, help_text="Maximum tokens for LLM responses.")
    prompt = models.ForeignKey(
        'prompts.Prompt',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="conversations",
        help_text="Associated prompt for this conversation."
    )

    active_objects = ActiveObjectsManager()


    def save(self, *args, **kwargs):
        if not self.conversation_id:
            self.conversation_id = "".join(
                random.choices(string.ascii_uppercase + string.digits, k=5)
            )
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Conversation {self.conversation_id}"

class Message(BaseModel):
    conversation = models.ForeignKey(
        Conversation,
        on_delete=models.CASCADE,
        related_name="messages",
        help_text="Corresponding conversation."
    )
    sender_type = models.IntegerField(
        choices=SenderType.choices,
        help_text="Type of sender (User or AI)."
    )
    sender = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        help_text="Name or identifier of the sender."
    )
    message = models.TextField(help_text="Content of the message.")
    llm = models.ForeignKey(
        'conversations.LLM',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="messages",
        help_text="The LLM used to generate this message (null for user messages)."
    )

    files = models.ManyToManyField(
        'files.File',
        blank=True,
        related_name='chat_messages',
        help_text="Files referenced in this message"
    )
    
    input_tokens = models.PositiveIntegerField(
        null=True,
        blank=True,
        help_text="Number of input tokens used in the LLM request."
    )
    output_tokens = models.PositiveIntegerField(
        null=True,
        blank=True,
        help_text="Number of output tokens generated by the LLM."
    )

    is_liked = models.BooleanField(
        default=False,
        help_text="Whether this message has been liked by the user."
    )
    is_disliked = models.BooleanField(
        default=False,
        help_text="Whether this message has been disliked by the user."
    )
    is_edited = models.BooleanField(
        default=False,
        help_text="Whether this message has been edited by the user (applies to user messages only)."
    )
    is_regenerated = models.BooleanField(
        default=False,
        help_text="Whether this message has been regenerated (applies to AI messages only)."
    )
    original_message = models.TextField(
        blank=True,
        null=True,
        help_text="Original content of the message before editing or regeneration."
    )

    active_objects = ActiveObjectsManager()

    @property
    def sender_name(self):
        """
        Returns the display name of the sender.
        If sender is provided, use that.
        Otherwise fall back to predefined labels based on sender_type.
        """
        if self.sender:
            return self.sender
        elif self.sender_type == SenderType.AI_ASSISTANT:
            return SenderType.AI_ASSISTANT.label
        else:
            return self.conversation.user.email

    @property
    def short_message(self):
        return self.message[:30] + "..." if len(self.message) > 30 else self.message

    def __str__(self):
        return f"{self.sender_name} ({self.short_message})"

class Snippet(BaseModel):
    """
    Model to track retrieved snippets from Pinecone vector search.
    """
    message = models.ForeignKey(
        Message,
        on_delete=models.CASCADE,
        related_name="snippets",
        help_text="The message this snippet was retrieved for."
    )
    file = models.ForeignKey(
        'files.File',
        on_delete=models.CASCADE,
        related_name="snippets",
        help_text="The file this snippet belongs to."
    )
    text = models.TextField(
        help_text="The text content of the snippet (chunk)."
    )
    similarity_score = models.FloatField(
        help_text="The similarity score of the snippet to the query."
    )
    chunk_index = models.PositiveIntegerField(
        help_text="The index of the chunk in the original file."
    )

    active_objects = ActiveObjectsManager()

    def __str__(self):
        return f"Snippet for Message {self.message.id} from File {self.file.id} (Score: {self.similarity_score})"