# Generated by Django 5.1.12 on 2026-01-13 04:22

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conversations", "0051_publicfeedbacksource_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this server (e.g., 'Slack')",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier (e.g., 'slack')", unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this server provides"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier for frontend (e.g., 'slack', 'github')",
                        max_length=50,
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        help_text="Command to run (e.g., 'npx')", max_length=255
                    ),
                ),
                (
                    "args",
                    models.JSONField(
                        default=list,
                        help_text="Command arguments as JSON array (e.g., ['-y', '@modelcontextprotocol/server-slack'])",
                    ),
                ),
                (
                    "required_credentials",
                    models.JSONField(
                        default=list,
                        help_text='\n        Schema for required credentials as JSON array. Example:\n        [\n            {"key": "SLACK_BOT_TOKEN", "label": "Bot Token", "type": "password", "placeholder": "xoxb-...", "required": true},\n            {"key": "SLACK_TEAM_ID", "label": "Team ID", "type": "text", "required": false}\n        ]\n        ',
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP Server",
                "verbose_name_plural": "MCP Servers",
                "ordering": ["name"],
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MCPToolExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "tool_name",
                    models.CharField(
                        help_text="Name of the tool that was called (e.g., 'send_message')",
                        max_length=255,
                    ),
                ),
                (
                    "tool_arguments",
                    models.JSONField(
                        default=dict, help_text="Arguments passed to the tool"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        help_text="Execution status",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, help_text="Tool response/result", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if execution failed"
                    ),
                ),
                (
                    "execution_time_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Execution time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Conversation context (if from LLM)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_tool_executions",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        help_text="Message that triggered this tool call (if from LLM)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_tool_executions",
                        to="conversations.message",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        help_text="MCP server the tool belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_executions",
                        to="mcp.mcpserver",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who executed this tool",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_tool_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP Tool Execution",
                "verbose_name_plural": "MCP Tool Executions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "server"], name="mcp_mcptool_user_id_4b4b9b_idx"
                    ),
                    models.Index(
                        fields=["status"], name="mcp_mcptool_status_221375_idx"
                    ),
                    models.Index(
                        fields=["tool_name"], name="mcp_mcptool_tool_na_354ab8_idx"
                    ),
                ],
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="UserMCPConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "encrypted_credentials",
                    models.JSONField(
                        default=dict,
                        help_text="Encrypted credentials as JSON object (keys are credential names, values are encrypted)",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this connection was used to call a tool",
                        null=True,
                    ),
                ),
                (
                    "cached_tools",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Cached tool definitions as fallback",
                    ),
                ),
                (
                    "tools_cached_at",
                    models.DateTimeField(
                        blank=True, help_text="When tools were last cached", null=True
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        help_text="MCP server this connection is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_connections",
                        to="mcp.mcpserver",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this connection",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User MCP Connection",
                "verbose_name_plural": "User MCP Connections",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "server"], name="mcp_usermcp_user_id_e7dfec_idx"
                    )
                ],
                "unique_together": {("user", "server")},
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
