# Generated by Django 5.1.12 on 2026-01-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpserver",
            name="credentials_help_url",
            field=models.URLField(
                blank=True,
                help_text="URL to documentation/guide on how to get credentials for this server",
            ),
        ),
    ]
