# Generated by Django 5.1.12 on 2026-01-14 02:16

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0002_mcpserver_credentials_help_url"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="mcptoolexecution",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="usermcpconnection",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="setup_guide",
            field=models.TextField(
                blank=True,
                help_text="Markdown-formatted setup instructions shown in the connection modal",
            ),
        ),
    ]
