# Generated by Django 5.1.12 on 2026-01-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0003_add_setup_guide"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpserver",
            name="extra_env_vars",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        Additional environment variables to set when spawning this server. Example:\n        {"SLACK_MCP_ADD_MESSAGE_TOOL": "true", "SLACK_MCP_DEBUG": "1"}\n        These are admin-configured, not user-provided.\n        ',
            ),
        ),
    ]
