# Generated by Django 5.1.12 on 2026-01-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0004_add_extra_env_vars"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpserver",
            name="docker_image",
            field=models.CharField(
                blank=True,
                help_text="Docker image to use in production (e.g., 'dare-mcp-slack:latest')",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="mcpserver",
            name="command",
            field=models.CharField(
                help_text="Command to run in dev mode (e.g., 'npx')", max_length=255
            ),
        ),
    ]
