# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0005_add_docker_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpserver",
            name="transport",
            field=models.CharField(
                choices=[
                    ("stdio", "Stdio"),
                    ("streamable_http", "Streamable HTTP"),
                ],
                default="stdio",
                help_text="How DARE connects to this MCP server",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("credentials", "Credentials"),
                    ("none", "None"),
                    ("bearer", "Bearer token"),
                    ("oauth2", "OAuth 2.0"),
                ],
                default="credentials",
                help_text="How users authenticate to this MCP server",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="remote_url",
            field=models.URLField(
                blank=True,
                help_text="Remote MCP endpoint for streamable HTTP servers",
            ),
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="remote_headers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Non-secret headers to send to remote MCP servers",
            ),
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="oauth_authorize_url",
            field=models.URLField(
                blank=True,
                help_text="OAuth authorization endpoint for remote MCP servers",
            ),
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="oauth_token_url",
            field=models.URLField(
                blank=True,
                help_text="OAuth token and refresh endpoint for remote MCP servers",
            ),
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="oauth_registration_url",
            field=models.URLField(
                blank=True,
                help_text="OAuth dynamic client registration endpoint, when supported",
            ),
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="oauth_scope",
            field=models.CharField(
                blank=True,
                help_text="OAuth scopes to request",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="oauth_client_id",
            field=models.CharField(
                blank=True,
                help_text="OAuth client ID if dynamic registration is not used",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="usermcpconnection",
            name="auth_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Non-secret connection metadata such as OAuth expiry and account identity",
            ),
        ),
    ]

