# Generated by Codex on 2026-05-24

from django.db import migrations


def seed_remote_research_servers(apps, schema_editor):
    MCPServer = apps.get_model("mcp", "MCPServer")

    MCPServer._default_manager.update_or_create(
        slug="consensus",
        defaults={
            "name": "Consensus",
            "description": (
                "Search peer-reviewed research papers with filters for study type, "
                "publication year, human studies, sample size, and medical mode."
            ),
            "icon": "consensus",
            "transport": "streamable_http",
            "auth_type": "oauth2",
            "docker_image": "",
            "command": "true",
            "args": [],
            "remote_url": "https://mcp.consensus.app/mcp",
            "remote_headers": {},
            "oauth_authorize_url": "https://consensus.app/oauth/authorize",
            "oauth_token_url": "https://consensus.app/oauth/token",
            "oauth_registration_url": "https://consensus.app/oauth/register/",
            "oauth_scope": "search",
            "oauth_client_id": "",
            "required_credentials": [],
            "credentials_help_url": "https://docs.consensus.app/docs/mcp",
            "extra_env_vars": {},
            "setup_guide": (
                "## Consensus MCP\n\n"
                "Consensus exposes a hosted Streamable HTTP MCP server at "
                "`https://mcp.consensus.app/mcp`.\n\n"
                "Consensus requires OAuth for the live MCP endpoint. DARE will "
                "dynamically register an OAuth client when the first user connects, "
                "then each user signs in with their own Consensus account."
            ),
            "is_active": True,
            "is_deleted": False,
        },
    )

    MCPServer._default_manager.update_or_create(
        slug="scite",
        defaults={
            "name": "Scite",
            "description": (
                "Search scientific literature and inspect citation context, including "
                "supporting, mentioning, and contrasting Smart Citation signals."
            ),
            "icon": "scite",
            "transport": "streamable_http",
            "auth_type": "oauth2",
            "docker_image": "",
            "command": "true",
            "args": [],
            "remote_url": "https://api.scite.ai/mcp",
            "remote_headers": {},
            "oauth_authorize_url": "https://api.scite.ai/mcp/oauth/authorize",
            "oauth_token_url": "https://api.scite.ai/mcp/oauth/token",
            "oauth_registration_url": "https://api.scite.ai/mcp/oauth/register",
            "oauth_scope": "mcp",
            "oauth_client_id": "",
            "required_credentials": [],
            "credentials_help_url": "https://scite.ai/mcp",
            "extra_env_vars": {},
            "setup_guide": (
                "## Scite MCP\n\n"
                "Scite exposes a hosted Streamable HTTP MCP server at "
                "`https://api.scite.ai/mcp` and requires a Scite subscription for MCP access.\n\n"
                "DARE will dynamically register an OAuth client when the first user connects, "
                "then each user signs in with their own Scite account."
            ),
            "is_active": True,
            "is_deleted": False,
        },
    )


def unseed_remote_research_servers(apps, schema_editor):
    MCPServer = apps.get_model("mcp", "MCPServer")
    MCPServer._default_manager.filter(slug__in=["consensus", "scite"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0006_remote_mcp_support"),
    ]

    operations = [
        migrations.RunPython(seed_remote_research_servers, unseed_remote_research_servers),
    ]
