# Generated by Django 5.1.12 on 2026-06-11 06:31

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0007_seed_remote_research_mcp_servers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GatewayFetch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "tool",
                    models.CharField(
                        help_text="Gateway tool name (e.g. 'fetch_page', 'scite__search_literature')",
                        max_length=255,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Fetched page URL (blank for search-style tools)",
                        max_length=1000,
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="DOI extracted from a doi.org URL, when present",
                        max_length=255,
                    ),
                ),
                (
                    "arguments",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arguments the tool was called with",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Complete, untrimmed response text"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User whose gateway served this call",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gateway_fetches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gateway Fetch",
                "verbose_name_plural": "Gateway Fetches",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "tool"], name="mcp_gateway_user_id_37d892_idx"
                    ),
                    models.Index(fields=["doi"], name="mcp_gateway_doi_d62c6c_idx"),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
