# Generated by Django 5.1.12 on 2026-06-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0008_gatewayfetch"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatewayfetch",
            name="error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Failure reason when the gateway call errored (blank on success)",
            ),
        ),
    ]
