# Generated by Django 5.1.12 on 2026-07-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0009_gatewayfetch_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewayfetch',
            name='run_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Hermes session id that made this call (DARE's '<hermes_session_id>-r<run_id>'), when the agent runtime forwards it — lets the run audit attribute each row to its exact run instead of matching by time window. Blank when not forwarded.", max_length=255),
        ),
    ]
