# Generated by Django 5.1.12 on 2026-07-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0010_gatewayfetch_run_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewayfetch',
            name='call_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text="The agent's tool_use id for this call (forwarded via MCP _meta), matched exactly against the same id on the stream's tool.completed event — so the audit links each call to its own result, no guessing. Blank when not forwarded.", max_length=255),
        ),
    ]
