# Generated by Django 5.1.6 on 2025-03-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Version number of the prompt. Increments when cloned.",
            ),
        ),
    ]
