# Generated by Django 5.1.6 on 2025-03-27 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0002_prompt_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Original prompt this was cloned from.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="prompts.prompt",
            ),
        ),
    ]
