# Generated by Django 5.1.11 on 2026-02-09 16:40

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0003_prompt_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishedPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description for the library."
                    ),
                ),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prompt",
                    models.OneToOneField(
                        help_text="The original prompt being published.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published",
                        to="prompts.prompt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Published Prompt",
                "verbose_name_plural": "Published Prompts",
                "ordering": ["-published_at"],
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
