# Generated by Django 5.1.11 on 2026-02-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0004_publishedprompt"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="publishedprompt",
            managers=[],
        ),
    ]
