# Generated by Django 5.1.6 on 2025-03-05 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("endpoint", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "LLMs",
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("session_id", models.CharField(max_length=10, unique=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this chat session.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sender_type",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Player"), (2, "AI Assistant")],
                        null=True,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "chat_session",
                    models.ForeignKey(
                        help_text="Corresponding chat session.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chats.conversation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
