# Generated by Django 5.1.6 on 2025-03-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
        ("files", "0003_seed_default_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="files",
            field=models.ManyToManyField(
                blank=True,
                help_text="Files referenced in this message",
                related_name="chat_messages",
                to="files.file",
            ),
        ),
    ]
