# Generated by Django 5.1.6 on 2025-03-05 21:41

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_message_files"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="conversation",
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="message",
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="conversation",
            name="session_id",
            field=models.CharField(
                help_text="Unique session ID.", max_length=10, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Title of the conversation.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="user",
            field=models.ForeignKey(
                help_text="User who owns this chat session.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="llm",
            name="endpoint",
            field=models.URLField(
                blank=True, help_text="API endpoint for the LLM.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="llm",
            name="name",
            field=models.CharField(
                help_text="Name of the Language Model.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message",
            field=models.TextField(help_text="Content of the message."),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender_type",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Player"), (2, "AI Assistant")],
                help_text="Type of sender (User or AI).",
                null=True,
            ),
        ),
    ]
