# Generated by Django 5.1.6 on 2025-03-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_alter_conversation_managers_alter_message_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="llm",
            name="endpoint",
        ),
        migrations.AddField(
            model_name="llm",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the language model capabilities.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="llm",
            name="identifier",
            field=models.CharField(
                default="",
                help_text="Technical identifier used in API calls (e.g., claude-3.5-sonnet-20240307).",
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="llm",
            name="name",
            field=models.CharField(
                help_text="Display name of the Language Model.", max_length=255
            ),
        ),
    ]
