# Generated by Django 5.1.6 on 2025-03-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0004_remove_llm_endpoint_llm_description_llm_identifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.CharField(
                blank=True,
                help_text="Name or identifier of the sender.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender_type",
            field=models.IntegerField(
                choices=[(1, "Player"), (2, "AI Assistant")],
                default=1,
                help_text="Type of sender (User or AI).",
            ),
            preserve_default=False,
        ),
    ]
