# Generated by Django 5.1.6 on 2025-03-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0005_message_sender_alter_message_sender_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
