# Generated by Django 5.1.6 on 2025-03-07 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0006_message_is_active_message_is_deleted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="session_id",
        ),
        migrations.RemoveField(
            model_name="message",
            name="chat_session",
        ),
        migrations.AddField(
            model_name="conversation",
            name="conversation_id",
            field=models.CharField(
                default="",
                help_text="Unique conversation ID.",
                max_length=10,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                default="",
                help_text="Corresponding conversation.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chats.conversation",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="conversation",
            name="user",
            field=models.ForeignKey(
                help_text="User who owns this conversation.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
