# Generated by Django 5.1.12 on 2026-01-14 19:07

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conversations", "0053_add_message_tool_call"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DareTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this tool (e.g., 'Create Diagram')",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier (e.g., 'create_diagram')",
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this tool does"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier for frontend (e.g., 'diagram', 'chart')",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("visualization", "Visualization"),
                            ("analysis", "Analysis"),
                            ("utility", "Utility"),
                        ],
                        default="visualization",
                        help_text="Tool category for UI grouping",
                        max_length=50,
                    ),
                ),
                (
                    "function_name",
                    models.CharField(
                        help_text="The function name the LLM will call (e.g., 'create_diagram')",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "DARE Tool",
                "verbose_name_plural": "DARE Tools",
                "ordering": ["category", "name"],
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="DareToolExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "tool_call_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique ID from LLM tool call",
                        max_length=255,
                    ),
                ),
                (
                    "arguments",
                    models.JSONField(
                        default=dict, help_text="Arguments passed to the tool"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Execution status",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, help_text="Tool response/result", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if execution failed"
                    ),
                ),
                (
                    "execution_time_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Execution time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Conversation context (if from LLM)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dare_tool_executions",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        help_text="Message that triggered this tool call (if from LLM)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dare_tool_executions",
                        to="conversations.message",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        help_text="DARE tool that was executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="dare_tools.daretool",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who executed this tool (null for public bots)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dare_tool_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DARE Tool Execution",
                "verbose_name_plural": "DARE Tool Executions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "tool"], name="dare_tools__user_id_7236a4_idx"
                    ),
                    models.Index(
                        fields=["status"], name="dare_tools__status_0a9eec_idx"
                    ),
                    models.Index(
                        fields=["tool_call_id"], name="dare_tools__tool_ca_1d06a9_idx"
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
