# Generated by Django 5.1.12 on 2026-06-08 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Human-readable project title.", max_length=255
                    ),
                ),
                (
                    "question",
                    models.TextField(
                        blank=True,
                        help_text="The central research question driving this project.",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        blank=True,
                        help_text="Field or domain of inquiry (e.g. 'Bioethics').",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        help_text="Project workflow status (DARE-owned).",
                        max_length=32,
                    ),
                ),
                (
                    "enabled_tools",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Research tool keys enabled for this project (free-form list of strings).",
                    ),
                ),
                (
                    "standards_template",
                    models.CharField(
                        blank=True,
                        help_text="Soul-file starter template chosen at creation (e.g. 'research-ethics').",
                        max_length=64,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The researcher (scholar) who owns this project.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Project",
                "verbose_name_plural": "Research Projects",
                "ordering": ["-created_at"],
            },
        ),
    ]
