# Generated by Django 5.1.12 on 2026-06-09 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchAgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Agent role slug (e.g. 'scout', 'critic'); free-form for now.",
                        max_length=64,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("scout", "Scout"), ("chat", "Chat")],
                        help_text="Mode of this run, mirroring the session mode.",
                        max_length=16,
                    ),
                ),
                (
                    "task",
                    models.TextField(
                        blank=True, default="", help_text="The delegated task text."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="started",
                        help_text="Run lifecycle (Hermes-produced; free-form).",
                        max_length=32,
                    ),
                ),
                (
                    "soul_file_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Soul file version that governed this run (provenance).",
                        max_length=64,
                    ),
                ),
                (
                    "selected_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Explicitly chosen context: sourceIds, approvedKnowledgeIds, projectMemoryIds, conversationIds.",
                    ),
                ),
                (
                    "allowed_tools",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tool slugs this run was allowed to use.",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When the run started.", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the run finished (null while running).",
                        null=True,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Cumulative cost for the run.",
                        max_digits=12,
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error detail if the run failed.",
                    ),
                ),
                (
                    "hermes_run_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Correlating Hermes run id (set when Hermes is wired).",
                        max_length=255,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this run belongs to (denormalised for filtering).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to="research.researchproject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Scholar who initiated the run.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_agent_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Agent Run",
                "verbose_name_plural": "Research Agent Runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchAgentToolCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "tool",
                    models.CharField(
                        help_text="Tool/MCP slug invoked (e.g. 'consensus').",
                        max_length=128,
                    ),
                ),
                (
                    "arguments",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arguments passed to the tool (includes the query).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="success",
                        help_text="Outcome: 'success' or 'error' (free-form).",
                        max_length=16,
                    ),
                ),
                (
                    "result_summary",
                    models.TextField(
                        blank=True, default="", help_text="Brief summary of the result."
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration of the call in milliseconds.",
                        null=True,
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error detail if the call failed.",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        help_text="Run this tool call belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_calls",
                        to="research.researchagentrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Agent Tool Call",
                "verbose_name_plural": "Research Agent Tool Calls",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "mode",
                    models.CharField(
                        choices=[("scout", "Scout"), ("chat", "Chat")],
                        help_text="Delegation mode (DARE-owned): 'scout' or 'chat'.",
                        max_length=16,
                    ),
                ),
                (
                    "hermes_session_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Correlating Hermes session id (set when Hermes is wired).",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional human label (e.g. a chat session name).",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        help_text="Session lifecycle (DARE-owned).",
                        max_length=16,
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the most recent run in this session.",
                        null=True,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this session belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="research.researchproject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Scholar who owns this session.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Session",
                "verbose_name_plural": "Research Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="researchagentrun",
            name="session",
            field=models.ForeignKey(
                help_text="Session this run belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="research.researchsession",
            ),
        ),
    ]
