# Generated by Django 5.1.12 on 2026-06-09 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_researchagentrun_researchagenttoolcall_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (file name or source title).",
                        max_length=512,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Display kind, e.g. 'PDF', 'Book chapter', 'Report'.",
                        max_length=128,
                    ),
                ),
                (
                    "size_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable file size, e.g. '2.3 MB' (for uploads).",
                        max_length=64,
                    ),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of pages, when known.", null=True
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        default="upload",
                        help_text="Kind of source (free-form): upload/paper/book/article/other.",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                ("authors", models.CharField(blank=True, default="", max_length=512)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("venue", models.CharField(blank=True, default="", max_length=255)),
                ("doi", models.CharField(blank=True, default="", max_length=255)),
                ("url", models.CharField(blank=True, default="", max_length=1024)),
                ("abstract", models.TextField(blank=True, default="")),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who added this source (null if added by an agent).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this source belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="research.researchproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Source",
                "verbose_name_plural": "Research Sources",
                "ordering": ["-created_at"],
            },
        ),
    ]
