# Generated by Django 5.1.12 on 2026-06-09 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0003_researchsource"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SoulFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        default="Research standards",
                        help_text="Display name for the soul file.",
                        max_length=255,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        help_text="Project this soul file governs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soul_file",
                        to="research.researchproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soul File",
                "verbose_name_plural": "Soul Files",
            },
        ),
        migrations.CreateModel(
            name="SoulFileVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "version",
                    models.PositiveIntegerField(
                        help_text="Incrementing version number (1, 2, 3, ...)."
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The full text/markdown of the soul file at this version.",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Where this version came from: template:<key>/upload/empty/edit.",
                        max_length=64,
                    ),
                ),
                (
                    "change_note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional note describing the edit.",
                        max_length=512,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who authored this version (null if seeded/agent).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="soul_file_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "soul_file",
                    models.ForeignKey(
                        help_text="The soul file this version belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="research.soulfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soul File Version",
                "verbose_name_plural": "Soul File Versions",
                "ordering": ["-version"],
                "unique_together": {("soul_file", "version")},
            },
        ),
    ]
