# Generated by Django 5.1.12 on 2026-06-09 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0004_soulfile_soulfileversion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchMemoryProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "proposed_by_role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Agent role slug that proposed it (e.g. 'scout').",
                        max_length=64,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, default="", help_text="The proposed memory text."
                    ),
                ),
                (
                    "memory_type",
                    models.CharField(
                        blank=True,
                        default="projectMemory",
                        help_text="Scope of the proposed memory (free-form).",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="proposed",
                        help_text="Proposal lifecycle (DARE-owned).",
                        max_length=16,
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Scholar who accepted it, if accepted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_accepted_memory_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this proposal belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_proposals",
                        to="research.researchproject",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        help_text="Run that produced this proposal, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memory_proposals",
                        to="research.researchagentrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Memory Proposal",
                "verbose_name_plural": "Research Memory Proposals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchProjectMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "label",
                    models.CharField(
                        help_text="Short label, e.g. 'Working thesis'.", max_length=255
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True, default="", help_text="The memory content."
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="manual",
                        help_text="Where it came from: manual/proposal/agent (free-form).",
                        max_length=32,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who captured this memory (null if from an agent).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_memory_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this memory belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_snapshots",
                        to="research.researchproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Project Memory",
                "verbose_name_plural": "Research Project Memory",
                "ordering": ["-created_at"],
            },
        ),
    ]
