# Generated by Django 5.1.12 on 2026-06-09 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0005_researchmemoryproposal_researchprojectmemory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        help_text="Author of the message: user or assistant.",
                        max_length=16,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, default="", help_text="The message text."
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this message belongs to (denormalised).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="research.researchproject",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        help_text="The run that produced this message (assistant turns).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to="research.researchagentrun",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Chat session this message belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="research.researchsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The scholar whose chat this is.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Chat Message",
                "verbose_name_plural": "Research Chat Messages",
                "ordering": ["created_at"],
            },
        ),
    ]
