# Generated by Django 5.1.12 on 2026-06-09 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0006_researchchatmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchStagingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        default="sourceCandidate",
                        help_text="Type of staged item (free-form; default 'sourceCandidate').",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                ("authors", models.CharField(blank=True, default="", max_length=512)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("venue", models.CharField(blank=True, default="", max_length=255)),
                ("doi", models.CharField(blank=True, default="", max_length=255)),
                ("url", models.CharField(blank=True, default="", max_length=1024)),
                ("abstract", models.TextField(blank=True, default="")),
                ("content", models.TextField(blank=True, default="")),
                ("rationale", models.TextField(blank=True, default="")),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Agent's relevance confidence, 0.0–1.0.",
                        null=True,
                    ),
                ),
                ("confidence_rationale", models.TextField(blank=True, default="")),
                (
                    "evidence_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="supporting/disputing/partial/tangential/unverifiable (free-form).",
                        max_length=32,
                    ),
                ),
                ("citation_context", models.TextField(blank=True, default="")),
                (
                    "provenance",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{tool, query, retrievedAt, soulFileId, soulFileVersion, role, runId}.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("staged", "Staged"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("later", "Later"),
                        ],
                        default="staged",
                        help_text="Review status (DARE-owned).",
                        max_length=16,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("later_reason", models.TextField(blank=True, default="")),
                (
                    "critic_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Critic pressure-test output, when 'Ask Critic' has run.",
                    ),
                ),
                (
                    "review_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Free-form review annotations.",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this candidate belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staging_items",
                        to="research.researchproject",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        help_text="The run that produced this item, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staging_items",
                        to="research.researchagentrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Staging Item",
                "verbose_name_plural": "Research Staging Items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchKnowledgeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("content", models.TextField(blank=True, default="")),
                ("rationale", models.TextField(blank=True, default="")),
                (
                    "provenance",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provenance carried over from the staging item.",
                    ),
                ),
                (
                    "soul_file_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Soul-file version that governed the approved item.",
                        max_length=64,
                    ),
                ),
                (
                    "used_in",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Sections of the project this source supports.",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The scholar who approved it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_approved_knowledge",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this knowledge belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_items",
                        to="research.researchproject",
                    ),
                ),
                (
                    "source_staging_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staging item this was promoted from.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_items",
                        to="research.researchstagingitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Knowledge Item",
                "verbose_name_plural": "Research Knowledge Items",
                "ordering": ["-created_at"],
            },
        ),
    ]
