# Generated by Django 5.1.12 on 2026-06-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0007_researchstagingitem_researchknowledgeitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchagentrun",
            name="status_detail",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable live progress line (e.g. 'Searching the web…').",
                max_length=255,
            ),
        ),
    ]
