# Generated by Django 5.1.12 on 2026-06-09 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0008_researchagentrun_status_detail"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "artifact_type",
                    models.CharField(
                        help_text="Renderer key: diagram | html | svg | excalidraw | … (free-form).",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Raw artifact payload (mermaid/svg/html text, or scene JSON).",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="hermes",
                        help_text="Who produced it: 'hermes' or 'dare'.",
                        max_length=32,
                    ),
                ),
                ("provenance", models.JSONField(blank=True, default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this artifact belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="research.researchproject",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        help_text="Run that produced this artifact, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifacts",
                        to="research.researchagentrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Artifact",
                "verbose_name_plural": "Research Artifacts",
                "ordering": ["-created_at"],
            },
        ),
    ]
