# Generated by Django 5.1.12 on 2026-06-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0009_researchartifact"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchagentrun",
            name="usage",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Token usage reported by the agent runtime (input_tokens / output_tokens / total_tokens).",
            ),
        ),
    ]
