# Generated by Django 5.1.12 on 2026-06-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0010_researchagentrun_usage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchagentrun",
            name="mode",
            field=models.CharField(
                choices=[
                    ("scout", "Scout"),
                    ("chat", "Chat"),
                    ("artifact", "Artifact"),
                ],
                help_text="Mode of this run, mirroring the session mode.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="researchsession",
            name="mode",
            field=models.CharField(
                choices=[
                    ("scout", "Scout"),
                    ("chat", "Chat"),
                    ("artifact", "Artifact"),
                ],
                help_text="Delegation mode (DARE-owned): 'scout' or 'chat'.",
                max_length=16,
            ),
        ),
    ]
