# Generated by Django 5.1.12 on 2026-06-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0012_researchagenttoolcall_result_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchproject",
            name="hermes_base_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Per-project Hermes gateway URL (its own profile = isolated agent memory + the owner's tools). Blank uses the shared default gateway.",
            ),
        ),
    ]
