# Generated by Django 5.1.12 on 2026-06-22 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0013_researchproject_hermes_base_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchThesisSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "stance",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="How the source bears on the thesis: supporting/disputing/partial/… (free-form).",
                        max_length=32,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The scholar who established the link.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_thesis_source_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="The durable source that bears on the thesis.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thesis_links",
                        to="research.researchknowledgeitem",
                    ),
                ),
                (
                    "thesis",
                    models.ForeignKey(
                        help_text="The thesis / open question / decision.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="research.researchprojectmemory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Thesis-Source Link",
                "verbose_name_plural": "Research Thesis-Source Links",
                "ordering": ["-created_at"],
                "unique_together": {("thesis", "source")},
            },
        ),
    ]
