# Generated by Django 5.1.6 on 2025-03-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="tags",
        ),
        migrations.AddField(
            model_name="file",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Custom tags for categorizing and filtering files",
                related_name="files",
                to="files.tag",
            ),
        ),
    ]
