# Generated by Django 5.1.6 on 2025-03-05 03:30

from django.db import migrations

def create_default_tags(apps, schema_editor):
    # Get the Tag model
    Tag = apps.get_model('files', 'Tag')

    # Define the default tags
    default_tags = [
        'Favorite',
        'Important',
        'Personal',
        'Work',
        'Archived'
    ]
    
    # Create default tags with user=None
    for label in default_tags:
        Tag.objects.get_or_create(label=label, user=None)

def reverse(apps, schema_editor):

    Tag = apps.get_model('your_app_name', 'Tag')
    Tag.objects.filter(user=None).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_remove_file_tags_file_tags"),
    ]

    operations = [
        migrations.RunPython(create_default_tags, reverse_code=reverse),
    ]
