# Generated by Django 5.1.6 on 2025-03-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_seed_default_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="job_id",
            field=models.CharField(
                blank=True,
                help_text="Redis Queue Job ID for tracking background processing",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Processing"), (1, "Processed"), (2, "Failed")],
                default=0,
                help_text="Processing status of the file",
            ),
        ),
    ]
