# Generated by Django 5.1.8 on 2025-05-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_file_vector_db_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                help_text="The actual file content", max_length=255, upload_to="files/"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.CharField(
                blank=True,
                help_text="MIME type of the file (e.g., application/pdf, image/jpeg)",
                max_length=150,
                null=True,
            ),
        ),
    ]
