# Generated by Django 5.1.11 on 2025-07-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if file processing failed', null=True),
        ),
    ]
