# Generated by Django 5.1.12 on 2025-10-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_file_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_media',
            field=models.BooleanField(default=False, help_text='Flag indicating if this file is a media file (image/video) that should not be vectorized'),
        ),
        migrations.AddField(
            model_name='file',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], help_text='Type of media file: image, video, or document', max_length=50, null=True),
        ),
    ]
