# Generated by Django 5.1.12 on 2025-10-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_file_is_media_file_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='generation_cost',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Cost in USD for generating this image', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='generation_params',
            field=models.JSONField(blank=True, help_text='Generation parameters: model, size, quality, style, etc.', null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='generation_prompt',
            field=models.TextField(blank=True, help_text='Original prompt used to generate this image (for AI-generated images)', null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='is_generated',
            field=models.BooleanField(default=False, help_text='Flag indicating if this file was AI-generated (e.g., via DALL-E)'),
        ),
        migrations.AddField(
            model_name='file',
            name='revised_prompt',
            field=models.TextField(blank=True, help_text='Revised/enhanced prompt returned by DALL-E during generation', null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('generated_image', 'Generated Image')], help_text='Type of media file: image, video, document, or generated_image', max_length=50, null=True),
        ),
    ]
