# Generated by Django 5.1.12 on 2025-11-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_file_generation_cost_file_generation_params_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user', 'is_deleted', 'is_active'], name='file_user_status_idx'),
        ),
    ]
