# Generated by Django 5.1.12 on 2025-12-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_add_composite_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='is_media',
            field=models.BooleanField(default=False, help_text='Flag indicating if this file is a media file (image/video/audio) that should not be vectorized'),
        ),
        migrations.AlterField(
            model_name='file',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('generated_image', 'Generated Image')], help_text='Type of media file: image, video, audio, document, or generated_image', max_length=50, null=True),
        ),
    ]
