# Generated by Django 5.1.15 on 2026-01-27 11:22

import core.storage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0012_add_audio_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="storage_backend",
            field=models.IntegerField(
                choices=[(1, "Local FileSystem"), (2, "SyftBox Distributed Storage")],
                default=1,
                help_text="Storage backend for this file (local or SyftBox)",
                verbose_name="Storage Backend",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=core.storage.fields.DynamicStorageFileField(
                help_text="The actual file content", max_length=255, upload_to="files/"
            ),
        ),
    ]
