# Generated by Django 5.1.15 on 2026-02-26 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0013_file_storage_backend_alter_file_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                help_text="Original file this was copied/imported from (lineage tracking)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copies",
                to="files.file",
                verbose_name="Source File",
            ),
        ),
        migrations.CreateModel(
            name="FileShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ForeignKey(
                        help_text="The SyftBox file being shared",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="files.file",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        help_text="User who shared the file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who received access. Null means shared with everyone (all platform users).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("file", "shared_with")},
            },
        ),
    ]
