# Generated by Django 5.1.12 on 2026-01-27 05:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the agent", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the agent's purpose",
                    ),
                ),
                (
                    "elevenlabs_agent_id",
                    models.CharField(
                        blank=True,
                        help_text="ElevenLabs agent ID (set after creation via API)",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "voice_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ElevenLabs voice ID to use",
                        max_length=100,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="System prompt / instructions for the agent"
                    ),
                ),
                (
                    "first_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Initial greeting message from the agent",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        help_text="LLM temperature setting",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(2.0),
                        ],
                    ),
                ),
                (
                    "max_duration_seconds",
                    models.PositiveIntegerField(
                        default=1800,
                        help_text="Maximum conversation duration in seconds (informational)",
                    ),
                ),
                (
                    "exam_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Title of the exam",
                        max_length=255,
                    ),
                ),
                (
                    "exam_instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Instructions shown to users before starting",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("active", "Active")],
                        default="draft",
                        help_text="Agent status (active = accessible to all users)",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this agent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "elevenlabs_conversation_id",
                    models.CharField(
                        help_text="ElevenLabs conversation ID",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the conversation started"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, help_text="When the conversation ended", null=True
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, help_text="Total duration in seconds", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "transcript",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Full conversation transcript",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="voice.voiceagent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="voiceagent",
            index=models.Index(
                fields=["user", "status"], name="voice_voice_user_id_20b50f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voiceagent",
            index=models.Index(
                fields=["elevenlabs_agent_id"], name="voice_voice_elevenl_a4871e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voiceagent",
            index=models.Index(fields=["status"], name="voice_voice_status_43a6d6_idx"),
        ),
        migrations.AddIndex(
            model_name="voiceconversation",
            index=models.Index(
                fields=["agent", "user"], name="voice_voice_agent_i_996df4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voiceconversation",
            index=models.Index(
                fields=["elevenlabs_conversation_id"],
                name="voice_voice_elevenl_21226e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="voiceconversation",
            index=models.Index(
                fields=["user", "status"], name="voice_voice_user_id_c1daa9_idx"
            ),
        ),
    ]
