# Generated by Django 5.1.12 on 2026-01-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceagent',
            name='conversation_config',
            field=models.JSONField(blank=True, default=dict, help_text='Full ElevenLabs conversation_config JSON'),
        ),
        migrations.AlterField(
            model_name='voiceagent',
            name='max_duration_seconds',
            field=models.PositiveIntegerField(default=1800, help_text='Maximum conversation duration in seconds'),
        ),
    ]
