"""
Django settings for dare project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from datetime import timedelta
from config import env
from config.sentry import init_sentry

init_sentry(
    dsn=env.SENTRY_DSN,
)

SECRET_KEY = env.SECRET_KEY

DEBUG = env.DEBUG == "True"

ALLOWED_HOSTS = env.ALLOWED_HOSTS

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.contrib.sites",
]

LOCAL_APPS = [
    "users",
    "common",
    "files",
    "core",
    "conversations",
    "prompts",
    "workflows",
    "email_logs",
    "billing",
]

THIRD_PARTY_APPS = [
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "channels",
    'django_rq'
]

INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "dare.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(env.BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.template.context_processors.i18n",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SITE_ID = env.SITE_ID

# Email Setting
EMAIL_HOST = env.EMAIL_HOST
EMAIL_HOST_USER = env.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = env.EMAIL_HOST_PASSWORD
EMAIL_FROM = env.EMAIL_FROM
DEFAULT_FROM_EMAIL = EMAIL_FROM
EMAIL_PORT = env.EMAIL_PORT

if env.EMAIL_HOST_USER and env.EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = "email_logs.backends.LoggingResendEmailBackend"
elif env.EMAIL_HOST:
    EMAIL_BACKEND = "email_logs.backends.LoggingSMTPEmailBackend"
else:
    EMAIL_BACKEND = "email_logs.backends.LoggingConsoleEmailBackend"

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": (
        "djangorestframework_camel_case.render.CamelCaseJSONRenderer",
        "djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer",
    ),
    "DEFAULT_PARSER_CLASSES": (
        "djangorestframework_camel_case.parser.CamelCaseJSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 500, # TODO: temporarily increasing page size, until we add pagination on FE
    "JSON_UNDERSCOREIZE": {
        "ignore_keys": ("password1", "password2", "new_password1", "new_password2", "old_password"),
    },
}

AUTH_USER_MODEL = "users.User"

# Authentication (dj-rest-auth and allauth)
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_ADAPTER = "users.adapter.AccountAdapter"

SIMPLE_JWT = {
        "ACCESS_TOKEN_LIFETIME": timedelta(
        days=1
    ),  # TODO: Change to 1 hour or few mins when refresh logic is implemented
    "REFRESH_TOKEN_LIFETIME": timedelta(days=5),  # TODO: Change to 1 day
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
}

REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_HTTPONLY": False,
    "USER_DETAILS_SERIALIZER": "users.api.serializers.CustomUserDetailsSerializer",
    "REGISTER_SERIALIZER": "users.api.serializers.CustomRegisterSerializer",
    "PASSWORD_RESET_USE_SITES_DOMAIN": False,
    "OLD_PASSWORD_FIELD_ENABLED": True,
}

# logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
            "include_html": True,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["mail_admins"],
            "level": "ERROR",
            "propagate": True,
        },
    },
}

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
)

# Define the default ASGI application
ASGI_APPLICATION = "dare.asgi.application"
WSGI_APPLICATION = "dare.wsgi.application"

# Django appends a trailing slash to URLs lacking one, if it resolves to a valid view.
APPEND_SLASH = True

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

RQ_QUEUES = {
    'default': {
        'HOST': env.REDIS_HOST,
        'PORT': env.REDIS_PORT,
        'DB': env.REDIS_DB,
        'DEFAULT_TIMEOUT': 3600,
    },
}

RQ_SHOW_ADMIN_LINK = True

WEAVIATE = {
    'HOST': env.WEAVIATE_HOST,
    'PORT': env.WEAVIATE_PORT,
    'COLLECTION_NAME': env.WEAVIATE_COLLECTION_NAME,
    'SKIP_INIT_CHECKS': env.WEAVIATE_SKIP_INIT_CHECKS,
    'AUTOSCHEMA_ENABLED': env.WEAVIATE_AUTOSCHEMA_ENABLED
}