"""
Django settings for dare project.

Generated by 'django-admin startproject' and maintained on Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from datetime import timedelta
from config import env
from config.sentry import init_sentry

init_sentry(
    dsn=env.SENTRY_DSN,
)

SECRET_KEY = env.SECRET_KEY

DEBUG = env.DEBUG == "True"

ALLOWED_HOSTS = env.ALLOWED_HOSTS

# Internal API key for inter-service communication (SB backend -> DARE backend)
DARE_INTERNAL_KEY = env.DARE_INTERNAL_KEY

# Bot wallet routing is rolled out behind this flag. When False,
# finalize_ai_message uses the legacy path (User.billing_mode lookup only);
# bot-attribution columns are still written. When True, the bot router
# applies the chatter-pays / anonymous-falls-back-to-owner rule.
BOT_WALLET_ENFORCEMENT_ENABLED = bool(int(os.environ.get(
    'BOT_WALLET_ENFORCEMENT_ENABLED', '0',
) or '0'))

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.contrib.sites",
]

LOCAL_APPS = [
    "users",
    "common",
    "files",
    "core",
    "conversations",
    "prompts",
    "agents",
    "workflows",
    "email_logs",
    "billing",
    "notifications",
    "api_keys",
    "mcp",
    "dare_tools",
    "memory",
    "sharing",
    "feature_flags",
    "research",
]

THIRD_PARTY_APPS = [
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "channels",
    "django_rq",
    "drf_spectacular",
]

INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "dare.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(env.BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.template.context_processors.i18n",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SITE_ID = env.SITE_ID

# Email Setting
EMAIL_HOST = env.EMAIL_HOST
EMAIL_HOST_USER = env.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = env.EMAIL_HOST_PASSWORD
EMAIL_FROM = env.EMAIL_FROM
DEFAULT_FROM_EMAIL = EMAIL_FROM
EMAIL_PORT = env.EMAIL_PORT

if env.EMAIL_HOST_USER and env.EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = "email_logs.backends.LoggingResendEmailBackend"
elif env.EMAIL_HOST:
    EMAIL_BACKEND = "email_logs.backends.LoggingSMTPEmailBackend"
else:
    EMAIL_BACKEND = "email_logs.backends.LoggingConsoleEmailBackend"

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": (
        "djangorestframework_camel_case.render.CamelCaseJSONRenderer",
        "djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer",
    ),
    "DEFAULT_PARSER_CLASSES": (
        "djangorestframework_camel_case.parser.CamelCaseJSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 500, # TODO: temporarily increasing page size, until we add pagination on FE
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "JSON_UNDERSCOREIZE": {
        "ignore_keys": ("password1", "password2", "new_password1", "new_password2", "old_password"),
        # Preserve dict keys under these fields from camelCase conversion.
        # nodeStates is a dict keyed by user-generated node IDs (e.g. '-ybkjiGpAUdvp01WwZodV_9')
        # that contain underscores — camelize() would mangle them without this.
        "ignore_fields": ("nodeStates",),
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "DARE Platform API",
    "DESCRIPTION": "AI-powered research and conversation platform with multi-LLM support, real-time streaming, workflow automation, and file management.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "CAMELIZE_NAMES": True,
    "POSTPROCESSING_HOOKS": [
        "drf_spectacular.hooks.postprocess_schema_enums",
    ],
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": r"/api/",
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
    },
}

AUTH_USER_MODEL = "users.User"

# Authentication (dj-rest-auth and allauth)
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_ADAPTER = "users.adapter.AccountAdapter"

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        hours=12
    ),  # TODO: Change to 1 hour or few mins when refresh logic is implemented
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),  # TODO: Change to 1 day
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
}

REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_HTTPONLY": False,
    "USER_DETAILS_SERIALIZER": "users.api.serializers.CustomUserDetailsSerializer",
    "REGISTER_SERIALIZER": "users.api.serializers.CustomRegisterSerializer",
    "LOGIN_SERIALIZER": "users.api.serializers.CustomLoginSerializer",
    "PASSWORD_RESET_USE_SITES_DOMAIN": False,
    "OLD_PASSWORD_FIELD_ENABLED": True,
}

# logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "level": "DEBUG",
        },
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
            "include_html": True,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "mail_admins"],
            "level": "INFO",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "WARNING",  # Set to DEBUG to see all SQL queries
            "propagate": False,
        },
        "conversations": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "core": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "files": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "billing": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "users": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        # Suppress noisy socketio/engineio emit logs
        "socketio": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "engineio": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "async_server": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
)

# Define the default ASGI application
ASGI_APPLICATION = "dare.asgi.application"
WSGI_APPLICATION = "dare.wsgi.application"

# Django appends a trailing slash to URLs lacking one, if it resolves to a valid view.
APPEND_SLASH = True

REDIS_HOST = env.REDIS_HOST or "127.0.0.1"
REDIS_PORT = int(env.REDIS_PORT or 6379)
REDIS_DB = int(env.REDIS_DB or 1)
REDIS_PASSWORD = env.REDIS_PASSWORD or ""

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}" if REDIS_PASSWORD else f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
            ],
        },
    }
}

RQ_QUEUES = {
    'default': {
        'HOST': REDIS_HOST,
        'PORT': REDIS_PORT,
        'DB': REDIS_DB,
        'PASSWORD': REDIS_PASSWORD if REDIS_PASSWORD else None,
        'DEFAULT_TIMEOUT': 3600,
    },
    'scheduler': {
        'HOST': REDIS_HOST,
        'PORT': REDIS_PORT,
        'DB': REDIS_DB,
        'PASSWORD': REDIS_PASSWORD if REDIS_PASSWORD else None,
    },
    'simple_queue': {
        'HOST': REDIS_HOST,
        'PORT': REDIS_PORT,
        'DB': REDIS_DB,
        'PASSWORD': REDIS_PASSWORD if REDIS_PASSWORD else None,
        'DEFAULT_TIMEOUT': 3600,
    },
}

RQ_SHOW_ADMIN_LINK = True

# Shared cache. The default LocMemCache is per-process, so cached values aren't
# shared across uvicorn workers; Redis makes them visible to all. Shares the
# Channels/RQ DB, namespaced via KEY_PREFIX — avoid cache.clear() here, which
# FLUSHDBs the shared DB; delete specific keys instead.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": (
            f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
            if REDIS_PASSWORD
            else f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
        ),
        "KEY_PREFIX": "dare_cache",
    }
}

# File Upload Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB in bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB in bytes

WEAVIATE = {
    'HOST': env.WEAVIATE_HOST,
    'PORT': env.WEAVIATE_PORT,
    'COLLECTION_NAME': env.WEAVIATE_COLLECTION_NAME,
    'SKIP_INIT_CHECKS': env.WEAVIATE_SKIP_INIT_CHECKS,
    'AUTOSCHEMA_ENABLED': env.WEAVIATE_AUTOSCHEMA_ENABLED
}

# SyftBox Settings (distributed file storage)
SYFTBOX = {
    'ENABLED': env.SYFTBOX_ENABLED,
    'DATASITES_ROOT': env.SYFTBOX_DATASITES_ROOT,
    'APP_NAME': env.SYFTBOX_APP_NAME,
}

# Hermes agent runtime (delegated research-agent runtime for Research Mode)
HERMES_GATEWAY_URL = env.HERMES_GATEWAY_URL
HERMES_API_KEY = env.HERMES_API_KEY
HERMES_SYNC_SOUL = env.HERMES_SYNC_SOUL
HERMES_SOUL_PATH = env.HERMES_SOUL_PATH
