# Generated by Django 5.1.12 on 2025-10-17 22:45

import core.fields
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProviderAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "Openai"),
                            ("claude", "Claude"),
                            ("gemini", "Gemini"),
                            ("llama", "Llama"),
                        ],
                        help_text="LLM provider (e.g., OpenAI, Anthropic, Google, Meta)",
                        max_length=20,
                    ),
                ),
                (
                    "api_key",
                    core.fields.EncryptedCharField(
                        blank=True,
                        help_text="API key for this provider (stored encrypted using AES-256)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this API key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Provider API Key",
                "verbose_name_plural": "User Provider API Keys",
                "ordering": ["user", "provider"],
                "indexes": [
                    models.Index(
                        fields=["user", "provider"],
                        name="api_keys_us_user_id_aa60f4_idx",
                    )
                ],
                "unique_together": {("user", "provider")},
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
