# Generated by Django 5.1.12 on 2025-10-17 22:45

from django.db import migrations


def create_api_keys_for_existing_users(apps, schema_editor):
    """
    Create UserProviderAPIKey records for all existing users.

    This ensures that all existing users have API key slots for all providers,
    similar to how Wallet is auto-created for users.
    """
    User = apps.get_model('users', 'User')
    UserProviderAPIKey = apps.get_model('api_keys', 'UserProviderAPIKey')

    # Provider choices - must match conversations.constants.Provider
    PROVIDERS = ['openai', 'claude', 'gemini', 'llama']

    # Note: In migrations, models don't have custom managers, so we access _default_manager
    users_list = list(User._default_manager.all())

    # Collect API keys to create
    api_keys_to_create = []

    for user in users_list:
        for provider in PROVIDERS:
            # Create a key record for each provider for each user
            api_keys_to_create.append(
                UserProviderAPIKey(
                    user=user,
                    provider=provider,
                    api_key=None,
                    is_active=True
                )
            )

    # Bulk create for efficiency
    if api_keys_to_create:
        UserProviderAPIKey._default_manager.bulk_create(api_keys_to_create, ignore_conflicts=True)
        print(f"Created UserProviderAPIKey records for {len(users_list)} users ({len(PROVIDERS)} providers each)")


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by deleting all UserProviderAPIKey records
    that were created by this migration (ones with null api_key).
    """
    UserProviderAPIKey = apps.get_model('api_keys', 'UserProviderAPIKey')
    deleted_count, _ = UserProviderAPIKey._default_manager.filter(api_key__isnull=True).delete()
    print(f"Deleted {deleted_count} empty UserProviderAPIKey records")


class Migration(migrations.Migration):

    dependencies = [
        ("api_keys", "0001_initial"),
        ("users", "0016_user_billing_mode"),
    ]

    operations = [
        migrations.RunPython(
            create_api_keys_for_existing_users,
            reverse_migration
        ),
    ]
