# Generated by Django 5.1.12 on 2025-11-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_keys", "0002_create_api_keys_for_existing_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproviderapikey",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "Openai"),
                    ("claude", "Claude"),
                    ("gemini", "Gemini"),
                    ("llama", "Llama"),
                    ("custom", "Custom"),
                ],
                help_text="LLM provider (e.g., OpenAI, Anthropic, Google, Meta)",
                max_length=20,
            ),
        ),
    ]
