# Generated by Django 5.1.11 on 2025-07-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='metadata',
        ),
    ]
