# Generated by Django 5.1.11 on 2025-08-03 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_remove_metadata_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotificationReadStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "Unread"),
                            ("read", "Read"),
                            ("archived", "Archived"),
                        ],
                        default="read",
                        help_text="User's status for this notification",
                        max_length=10,
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user marked this notification as read",
                        null=True,
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        help_text="Notification this read status applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_read_statuses",
                        to="notifications.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who has this read status",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_read_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Notification Read Status",
                "verbose_name_plural": "User Notification Read Statuses",
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="notificatio_user_id_316550_idx"
                    ),
                    models.Index(
                        fields=["notification", "status"],
                        name="notificatio_notific_b56412_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_0e3dfd_idx"
                    ),
                ],
                "unique_together": {("user", "notification")},
            },
        ),
    ]
