# Generated by Django 5.1.12 on 2025-12-12 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_usernotificationreadstatus"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="source",
            field=models.CharField(
                choices=[("DARE", "DARE"), ("SocraticBots", "SocraticBots")],
                db_index=True,
                default="DARE",
                help_text="Target platform for this notification (DARE or SocraticBots)",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["source"], name="notificatio_source_9d1fc4_idx"),
        ),
    ]
