# Generated by Django 5.1.15 on 2026-03-24 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        help_text="Primary key of the shared entity"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional message from the sharer",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Type of the shared entity (Conversation, Workflow, Prompt)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        help_text="User who shared this item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_shared_by_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        help_text="User who received the share",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_shared_with_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shared Item",
                "verbose_name_plural": "Shared Items",
                "indexes": [
                    models.Index(
                        fields=["shared_with", "content_type"],
                        name="sharing_sha_shared__9b7c73_idx",
                    ),
                    models.Index(
                        fields=["shared_by", "content_type"],
                        name="sharing_sha_shared__97222e_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="sharing_sha_content_bc82d7_idx",
                    ),
                ],
                "unique_together": {("content_type", "object_id", "shared_with")},
            },
        ),
    ]
