# Generated by Django 5.1.15 on 2026-03-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shareditem",
            name="object_id",
            field=models.CharField(
                help_text="Identifier of the shared entity (PK or conversation_id)",
                max_length=100,
            ),
        ),
    ]
