# Generated by Django 5.1.12 on 2026-04-08 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharing", "0003_shareditem_group_sharing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="shareditem",
            new_name="sharing_sha_shared__3d6c5c_idx",
            old_name="sharing_sha_shared__group_ct_idx",
        ),
        migrations.AlterField(
            model_name="shareditem",
            name="shared_with",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific user who received the share (null for group shares)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items_shared_with_me",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
